### ISSUE TITLE
full dump to file

### ISSUE THREAD

**Issue by amg-web** [dimitri/pgcopydb#1]
Is it possible to backup full dump to file?

I was able to get small pre.dump and post.dump only

and one more, pgcopydb list tables did not ask for password and fail

**Comment by df7cb** [comment]
If you want a backup to file, use normal pg_dump (-Fc or possibly -Fd).

**Comment by df7cb** [comment]
The target database (db_prod) should be empty (no tables, no data) before restoring the dump into it.

**Comment by amg-web** [comment]
it was empty

**Comment by df7cb** [comment]
Also, that erroring statement doesn't look like it's coming from pg_dump. Is that your app talking to the database while the restore is running?

**Comment by amg-web** [comment]
no. application is down
