### ISSUE TITLE
What does "WARN  Failed to parse desc messages..." mean?

### ISSUE THREAD

**Issue by TLINDEN** [dimitri/pgcopydb#123]
Hello,

during a run of `pgcopydb copy-db --index-jobs=8 --table-jobs=8 --drop-if-exists` we get lots of warnings like these:
```
10:08:42 52 INFO  STEP 3: restore the pre-data section to the target database
[..]
10:08:42 52 WARN  Failed to parse desc "ACL pg_catalog FUNCTION pg_switch_wal() postgres" for ACL or COMMENT                                                                                    
10:08:42 52 WARN  Failed to parse desc "ACL pg_catalog FUNCTION pg_switch_wal() postgres"                                                                                                       
10:08:42 52 WARN  Failed to parse desc "ACL public FUNCTION pg_stat_statements_reset(userid oid, dbid oid, queryid bigint) postgres" for ACL or COMMENT                                         
10:08:42 52 WARN  Failed to parse desc "ACL public FUNCTION pg_stat_statements_reset(userid oid, dbid oid, queryid bigint) postgres"                                                            
10:08:42 52 WARN  Failed to parse desc "ACL public FUNCTION set_user(text) postgres" for ACL or COMMENT                                                                                         
10:08:42 52 WARN  Failed to parse desc "ACL public FUNCTION set_user(text) postgres" 
[..]
10:08:42 52 WARN  Failed to parse desc "ACL pg_catalog TABLE pg_stat_activity postgres"                                                                                                         
10:08:42 52 INFO   /usr/bin/pg_restore --dbname 'postgres://ftdbo@*.*.*.*:32001/logs?' --single-transaction --clean --if-exists --use-list /tmp/pgcopydb/schema/pre.list /tmp/pgcopydb/sche
ma/pre.dump                                                                                                                                                                                     
10:08:42 52 INFO  STEP 4: copy data from source to target in 1 sub-processes  
[..]
```

Restore on the target database seems to be complete. Do you have any idea what these warnigs are meaning?

We use pgcopydb version 0.9.

Thanks in advance,
Tom

**Comment by TLINDEN** [comment]
**Update**: we don't see these warnings with version 0.8.

**Comment by TLINDEN** [comment]
This is being caused by the function parse_archive_acl_or_comment, which expects:
```ACL -```
but gets:
```ACL```
so, the minus char is missing in our instance at least. We're using postgres 13.4.

**Comment by dimitri** [comment]
Hi @TLINDEN ; thanks for reporting an issue and following-up with it, diving into the code to better understand it. What's happening here is that pgcopydb needs to parse *some* of the ACL entries in the Postgres dump/restore archive format, though not all of them. To have a chance of improving my little parser, I decided I would WARN about entries that fail to parse.

So there is no impact at all in the behavior of pgcopydb (hence WARN, not ERROR), but it's enough of a problem that someone might want to report it, giving me a chance to go ahead and fix the parser. Let's see about adding support for more ACL descriptions then!

**Comment by TLINDEN** [comment]
Thanks a lot for the explanation @dimitri!
