### ISSUE TITLE
[bug][online] Integer, numeric replicated data inconsistency.

### ISSUE THREAD

**Issue by shubhamdhama** [dimitri/pgcopydb#127]
`pgcopydb` version: 0.8

LOGS:

```
22:51:20 12699 NOTICE pgsql.c:1079 [TARGET] INSERT INTO "public"."category" (category_id, name, last_update) VALUES (2.12902e+06, 'a5beaff653', '2022-09-27 22:50:32.109197');
22:51:20 12699 NOTICE pgsql.c:1079 [TARGET] INSERT INTO "public"."category" (category_id, name, last_update) VALUES (2.12902e+06, '0d83c94832', '2022-09-27 22:50:32.109197');
22:51:20 12699 ERROR pgsql.c:1139 [TARGET] ERROR:  duplicate key value violates unique constraint "category_pkey"
22:51:20 12699 ERROR pgsql.c:1139 [TARGET] DETAIL:  Key (category_id)=(2129020) already exists.
22:51:20 12699 ERROR pgsql.c:1142 SQL query: INSERT INTO "public"."category" (category_id, name, last_update) VALUES (2.12902e+06, '0d83c94832', '2022-09-27 22:50:32.109197')
22:51:20 12699 ERROR pgsql.c:1143 SQL params: 
22:51:20 12696 ERROR follow.c:151 Catch-up process 12699 has terminated [7]
```

Here the migration failed as it created problems for the primary key.

**Comment by shubhamdhama** [comment]
## Inconsistent `int` data
### How to reproduce

In source dvdrental database, have around 2 Million rows inserted in the `category` table to ensure the key's value is large enough. Then start the migration, and during the online phase insert any row. When the data is applied it causes the above issue.

A simple way to insert n number of rows (vary the second argument of `generate_series`) into `category` table.

```
psql -d $PGCOPYDB_SOURCE_PGURI -c "INSERT INTO category(name) SELECT left(md5(random() :: text), 10) FROM generate_series(1, 1000000) s(I);"
```

This is how I discovered the issue because it broke the primary key constraint on the target. Otherwise, such inconsistency will go unnoticed if the column is non-unique. So alternative way to reproduce is to insert a large integer value and it will be changed onto the target.

## Inconsistent float/double/numeric data

Now I'm seeing another serious issue somewhat related to this one,
### How to reproduce

Create a table like the one below, 

```sql
CREATE TABLE table1 (col1 serial primary key, col2 double precision, col3 bigint);
INSERT INTO table1(col2, col3) VALUES ('NaN', 1);
INSERT INTO table1(col2, col3) VALUES ('Infinity', 1);
INSERT INTO table1(col2, col3) VALUES ('-Infinity', 1);
INSERT INTO table1(col2, col3) VALUES ('11.111', 9223372036854775807);
```
and after starting the migration, again, insert the following rows,
```sql
INSERT INTO table1(col2, col3) VALUES ('NaN', 1);
INSERT INTO table1(col2, col3) VALUES ('Infinity', 1);
INSERT INTO table1(col2, col3) VALUES ('-Infinity', 1);
INSERT INTO table1(col2, col3) VALUES ('11.111', 9223372036854775807);
```

After replication target will look something like this

```
dvdrental2=# select * from table1;
 col1 |   col2    |        col3
------+-----------+---------------------
    1 |       NaN |                   1
    2 |  Infinity |                   1
    3 | -Infinity |                   1
    4 |    11.111 | 9223372036854775807
    5 |           |                   1
    6 |           |                   1
    7 |           |                   1
    8 |        11 | 9200000000000000000
(8 rows)
```

As you can see `NaN`, `Infinity`, and `-Infinity` are replicated as `null` in last 4 rows.

I think the issue lies in `wal2json`, where it converts these values to `null`,
https://github.com/eulerto/wal2json/blob/770872b890f9e122290f178e7c7bfa19ec7afa94/wal2json.c#L1272-L1277

this can also be seen in logs,
```
16:39:27 48187 TRACE ld_transform.c:348 stream_transform_file[11]: {"action":"I","xid":85889,"timestamp":"2022-10-31 16:38:20.533843+05:30","lsn":"6/4D255D10","schema":"public","table":"table1","columns":[{"name":"col1","type":"integer","value":5},{"name":"col2","type":"double precision","value":null},{"name":"col3","type":"bigint","value":1}]}
16:39:27 48187 TRACE ld_transform.c:348 stream_transform_file[16]: {"action":"I","xid":85891,"timestamp":"2022-10-31 16:38:27.629698+05:30","lsn":"6/4D25E7D0","schema":"public","table":"table1","columns":[{"name":"col1","type":"integer","value":6},{"name":"col2","type":"double precision","value":null},{"name":"col3","type":"bigint","value":1}]}
16:39:27 48187 TRACE ld_transform.c:348 stream_transform_file[19]: {"action":"I","xid":85892,"timestamp":"2022-10-31 16:38:31.312522+05:30","lsn":"6/4D25E890","schema":"public","table":"table1","columns":[{"name":"col1","type":"integer","value":7},{"name":"col2","type":"double precision","value":null},{"name":"col3","type":"bigint","value":1}]}
16:39:27 48187 TRACE ld_transform.c:348 stream_transform_file[22]: {"action":"I","xid":85893,"timestamp":"2022-10-31 16:38:35.050386+05:30","lsn":"6/4D25E988","schema":"public","table":"table1","columns":[{"name":"col1","type":"integer","value":8},{"name":"col2","type":"double precision","value":11.111},{"name":"col3","type":"bigint","value":9223372036854775807}]}
```

From the comment, I can see this is expected in `wal2json` so either we should fix it there or remove `wal2json` as a dependency and directly convert replicated data to SQL statements like this plugin does https://github.com/michaelpq/pg_plugins/tree/main/decoder_raw. We can use `decoder_raw` or tweak into `contrib/test_decoding`'s `tuple_to_stringinfo` function to generate direct SQL statements instead of
```
table public.xyz: UPDATE: id[integer]:1 c1[numeric]:NaN c2[double precision]:Infinity c3[double precision]:-Infinity
=>
UPDATE public.xyz SET c1 = 'NaN', c2 = 'Infinity', c3 = '-Infinity' WHERE id = 1
```
then will also get rid of the `transform` process (less complexity).

**Comment by shubhamdhama** [comment]
> From the comment, I can see this is expected in wal2json so either we should fix it there or remove wal2json as a dependency and directly convert replicated data to SQL statements like this plugin does https://github.com/michaelpq/pg_plugins/tree/main/decoder_raw. We can use decoder_raw or tweak into contrib/test_decoding's [tuple_to_stringinfo](https://github.com/postgres/postgres/blob/6e10631d1e6e350ba3f82b0bd3a29678f9f5badd/contrib/test_decoding/test_decoding.c#L526) function to generate direct SQL statements instead of current string.

Any new decoding plugin won't be available on managed services, so maybe `test_decoding` is our only option or fix in `wal2json`.

**Comment by dimitri** [comment]
> Any new decoding plugin won't be available on managed services, so maybe `test_decoding` is our only option or fix in `wal2json`.

I would like that `wal2json` had an option to pass numeric values as text string in the JSON object. Do you want to work on a patch to do that @shubhamdhama ?

**Comment by dimitri** [comment]
My understanding is that we can close this issue as solved: @shubhamdhama constributed a fix to wal2json, and we also have added support for test_decoding in pgcopydb. Consider re-opening with more information if needed.
