### ISSUE TITLE
Working around "permission denied for relation pg_authid issue"

### ISSUE THREAD

**Issue by levinotik** [dimitri/pgcopydb#135]
Thank you for this excellent tool. I'm having some trouble completing a copy from ab RDS database to postgres running in a local container

```shell
docker run --rm --network api_default -it dimitri/pgcopydb:v0.9 pgcopydb clone --table-jobs 8 --index-jobs 2 --source $PGCOPYDB_SOURCE_PGURI --target $PGCOPYDB_TARGET_PGURI
...
....
21:55:04 30 INFO   STEP 0: copy the source database roles
21:55:04 30 INFO    /usr/bin/pg_dumpall --roles-only --file /tmp/pgcopydb/schema/roles.sql --dbname 'postgres://...?'
21:55:05 30 ERROR  pg_dumpall: error: query failed: ERROR:  permission denied for relation pg_authid
21:55:05 30 ERROR  pg_dumpall: error: query was: SELECT oid, rolname, rolsuper, rolinherit, rolcreaterole, rolcreatedb, rolcanlogin, rolconnlimit, rolpassword, rolvaliduntil, rolreplication, rolbypassrls, pg_catalog.shobj_description(oid, 'pg_authid') as rolcomment, rolname = current_user AS is_current_user FROM pg_authid WHERE rolname !~ '^pg_' ORDER BY 2
21:55:05 30 ERROR  Failed to run pg_dump: exit code 1
21:55:05 30 ERROR  Failed to clone source database, see above for details
21:55:05 1 ERROR  clone process 30 has terminated [6]
21:55:06 1 WARN   Failed to clone the source database, see above for details
```

I've read the note on this in the documentation here https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_clone.html#postgres-privileges-superuser-and-dump-and-restore but I'm still unsure what the right way to resolve this issue is. 

In the past, when I've used `pg_dump` and `pg_restore` directly, I didn't seem to run into this issue.

Is there a way to perhaps limit the data/tables that are copied to only be those in the `public` schema? Or is other preferred way to deal with these permissions issues?

Thanks in advance.

**Comment by levinotik** [comment]
Looks like my best bet may be to define an exclusions file as documented [here](https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_config.html#filtering) like so?

```
[exclude-schema]
pg_catalog
pganalyze
```

**Comment by dimitri** [comment]
Hi @levinotik ; thanks for opening this issue. It seems to me that the behavior you indicate (calling into `pg_dumpall`) is only done when using the option `--roles`, and in your copy/paste I don't see that. It could be a bug somewhere causing the option to be on even when not specified, but I have to ask first: are you certain of your copy/paste above?

**Comment by levinotik** [comment]
Hi @dimitri thanks for the reply. That is strange. I _thought_ I had simply copy-pasted what I had done, but apparently not! I will give this another shot to confirm what I've pasted above and report back. Thank you.

**Comment by dimitri** [comment]
Closing this issue for triage. If more help is needed, please consider re-opening the issue with more information.
