### ISSUE TITLE
Pgcopydb list progress is not working for clone follow instance.

### ISSUE THREAD

**Issue by nakatlam** [dimitri/pgcopydb#138]
It fails with error 
ERROR Failed to parse JSON file \"<$TMPDIR>/pgcopydb/schema.json\""

As we look into deep, "pgcopydb clone follow" creates schema.json in TMPDIR root itself i.e., TMPDIR/schema.json
But the pbcopydb-list-progress searches for the schema.json in $TMPDIR/pgcopydb/ folder.

**Comment by dimitri** [comment]
Hi @nakatlam ; please provide detailed logs about the situation you're mentioning. I don't see in the code where that confusion would happen, so I need all the details : exact command, exact output, using `--debug` flag.
