### ISSUE TITLE
Support for large objects

### ISSUE THREAD

**Issue by ianchov** [dimitri/pgcopydb#14]
Hi @dimitri ,

Just tested latest master and i see that large objects are not transferred. Could you include the *-b* pg_dump option?

**Comment by dimitri** [comment]
Hi @ianchov ; thanks for testing very early versions of pgcopydb and providing feedback!

The design we have now is that we only use pg_dump and pg_restore for the schema parts, and try to be smarter than those tools when it comes to moving the data around (multiple workers without spilling to disk, parallel index creation even on the same table, etc). 

About large objects (aka blobs), I believe that pg_dump is only using one worker for all of them, and I also believe it should be possible to split the workload among the `--table-jobs` workers pretty easily, so I would rather implement that compared to letting pg_dump and pg_restore take care of moving large objects to disk, and then from disk.

Also, do you want to contribute support for large objects in pgcopydb?

**Comment by ianchov** [comment]
I am playing with large_objects and i have hit a problem with RDS.

If i export an object with psql -c '\lo_export OID filename' and then try to import it into an RDS:
psql -c '\lo_import OID filename' i get a random new oid number (not the one i specified as OID)..As it turns out on RDS the pg_largeobject and pg_largeobject_metadata tables are owner by rsaadmin and one can only use the functions lo_* without having permissions to modify  the table entries.
So at least from what i tried, one cannot move the large objects just like that. It needs to change their OIDs numbers into his tables.

**Comment by dimitri** [comment]
Thanks for providing this feedback! Can you have a look at what `pg_dump` and `pg_restore` would do in such a situation?

**Comment by ianchov** [comment]
So i tested pg_dump  from 9.6 and pg_restore to an RDS v12 and it works with the blobs. OIDs are mapped correctly.
I checked https://doxygen.postgresql.org/pg__dump_8c.html#a09cb1dcfe31e433e6dfd7dd417139677 and there it created the object and writes to it. So think i can write this python also but much better if you do it in pgcopydb

**Comment by dimitri** [comment]
Hi @ianchov ; large objects support is now in! At the moment, if you want to try it out you can either build from sources or use the CI/CD github packages that we provide, as a docker image:

```
$ docker pull ghcr.io/dimitri/pgcopydb:latest
$ echo "now check that the new command is available:"
$ docker run --rm -it ghcr.io/dimitri/pgcopydb:latest pgcopydb copy blobs --help
```

With the new command available, the processing of blobs is of course integrated transparently to the main `pgcopydb copy-db` command, you don't have to do anything extra. I included that command as a way for you to make sure you pulled the latest package with the support for large objects integrated.
