### ISSUE TITLE
pg_dump server version mismatch

### ISSUE THREAD

**Issue by Gogotchuri** [dimitri/pgcopydb#149]
Hi, this seems a great tool, tried to use it with the default docker command and had trouble.

19:12:03 15 ERROR  pg_dump: error: server version: 14.5; pg_dump version: 13.8 (Debian 13.8-0+deb11u1)
19:12:03 15 ERROR  pg_dump: error: aborting because of server version mismatch
19:12:03 15 ERROR  Failed to run pg_dump: exit code 1
19:12:03 15 ERROR  Failed to clone source database, see above for details
19:12:03 1 ERROR  clone process 15 has terminated [6]
19:12:03 1 WARN   Failed to clone the source database, see above for details
19:12:03 1 FATAL  Terminating all processes in our process group         

Can you help me with the issue?

**Comment by dimitri** [comment]
It seems like the docker image contains pg_dump version from Postgres 13.8. Try building a docker image with a version that matches your production environment, apparently 14.5. I suppose you will need your own Dockerfile for that.
