### ISSUE TITLE
Apply process never finishing as SQL statement with endpos is missing.

### ISSUE THREAD

**Issue by shubhamdhama** [dimitri/pgcopydb#154]
**Issue** along with 
In some cases, if we set the `endpos` LSN which lies between a transaction (before the LSN of the `COMMIT`), the streaming process writes an incomplete transaction to the `.json` file. For example if we insert 10 rows,
```sh
 psql -d $PGCOPYDB_SOURCE_PGURI -c "INSERT INTO category(name) SELECT left(md5(random() :: text), 10) FROM generate_series(1, 10) s(i);"
```
And set the endpos as `0/A6ED170`, the streaming process will stop after writing only 4 json lines (note the LSNs)

```json
{"action":"B","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED5E0","nextlsn":"0/A6ED610"}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED040","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":37},{"name":"name","type":"character varying(25)","value":"57d11d5746"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED0D0","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":38},{"name":"name","type":"character varying(25)","value":"84ff65dbd7"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED160","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":39},{"name":"name","type":"character varying(25)","value":"91efc32265"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
```

The transform process does the right thing further by not writing the corresponding SQL statements to the ".sql" file. So in this case, the streaming and transform processes finish. But apply process couldn't because a SQL statement with the meta-data containing LSN greater than endpos are not there.

**How to reproduce**

A way to reproduce is to put some sleep in between the writing of json to .json files. Then as soon as you see json for `INSERT` statements in logs, pick any `lsn` of any of those `INSERT`s and put that as an `endpos`.

**Comment by shubhamdhama** [comment]
I also like to mention the issue here is not just writing incomplete transactions when the streaming is stopped. We can also observe incomplete transactions if streaming gets interrupted in between a large transaction so we end up re-writing corresponding JSONs to the file e.g.

```json
{"action":"B","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED5E0","nextlsn":"0/A6ED610"}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED040","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":37},{"name":"name","type":"character varying(25)","value":"57d11d5746"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED0D0","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":38},{"name":"name","type":"character varying(25)","value":"84ff65dbd7"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED160","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":39},{"name":"name","type":"character varying(25)","value":"91efc32265"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED1F0","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":40},{"name":"name","type":"character varying(25)","value":"1ea9457155"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED280","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":41},{"name":"name","type":"character varying(25)","value":"385f4dd420"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"B","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED5E0","nextlsn":"0/A6ED610"}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED040","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":37},{"name":"name","type":"character varying(25)","value":"57d11d5746"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED0D0","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":38},{"name":"name","type":"character varying(25)","value":"84ff65dbd7"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED160","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":39},{"name":"name","type":"character varying(25)","value":"91efc32265"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"B","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED5E0","nextlsn":"0/A6ED610"}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED040","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":37},{"name":"name","type":"character varying(25)","value":"57d11d5746"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
{"action":"I","xid":4298,"timestamp":"2022-11-21 20:23:41.663598+05:30","lsn":"0/A6ED0D0","schema":"public","table":"category","columns":[{"name":"category_id","type":"integer","value":38},{"name":"name","type":"character varying(25)","value":"84ff65dbd7"},{"name":"last_update","type":"timestamp without time zone","value":"2022-11-21 20:23:41.662318"}]}
```
Here the streaming was interrupted multiple times and on restart it end up re-writing the jsons.
```log
20:28:24 13505 DEBUG  pgsql.c:3380: pgsql_stream_logical: endpos reached at 0/A6ED310
20:28:24 13505 INFO   pgsql.c:3584: Report write_lsn 0/A6ED280, flush_lsn 0/A6ED280, replay_lsn 0/0
20:28:24 13505 DEBUG  pgsql.c:3663: end position 0/A6ED170 reached by WAL record at 0/A6ED280
20:28:24 13505 ERROR  pgsql.c:3450: could not read COPY data: SSL connection has been closed unexpectedly

20:28:24 13505 ERROR  pgsql.c:1375: Failure from Postgres:
20:28:24 13505 ERROR  pgsql.c:1379: SSL connection has been closed unexpectedly
```

**Comment by shubhamdhama** [comment]
@dimitri I'm interested to work on this, please assign this to me if that's okay.

I'm thinking of what could be the right approach here,

Approach 1: In the streaming process, put the "json"s into a buffer and write it to the disk (.json file) only when we have the corresponding `COMMIT` statements. I don't like this approach because it will require awareness of the STREAMING ACTION in the streaming process which will make it more complex. Also, it will require communication to the apply process (maybe via sentinel table) that apply process should stop now (we can make apply column as an enum instead of a boolean).

Approach 2 (I'm preferring this)

Here let the streaming process be dumb and keep inserting data to the JSON files as it receives and use the transform process to determine which JSON should be converted to SQL or discarded.

In this function,
https://github.com/dimitri/pgcopydb/blob/8cc1882383db58397899ecbf922355bbd4de1e28/src/bin/pgcopydb/ld_transform.c#L278-L443

First, after a `BEGIN` we can only expect `COMMIT`, `INSERT`, `UPDATE` etc. but not again a `BEGIN`. So if we come across a `BEGIN`, drop the (invalid) transaction. This should handle re-writing incomplete transactions. 

(One doubt here is whether it is possible that we can write the complete transaction written to JSON file, then streaming got interrupted, and resuming the logical streaming happens from the start of this transaction, this could be another edge case).

Coming to the solution of the main issue, at the end of each file put a `NULL` SQL statement with the same meta-data as the last SQL statement (even if it's incomplete). And in
https://github.com/dimitri/pgcopydb/blob/main/src/bin/pgcopydb/ld_apply.c#L283-L289

we can put another `case` that interprets the `NULL` statements to detect `endpos` as we do in BEGIN case.

**Comment by shubhamdhama** [comment]
The approach "2" can be easier to implement IMO. But I will ask a high-level question, am I approaching this to patch for only this bug, and the issue is something more fundamental like simplifying this design?

**Comment by dimitri** [comment]
> I also like to mention the issue here is not just writing incomplete transactions when the streaming is stopped. We can also observe incomplete transactions if streaming gets interrupted in between a large transaction so we end up re-writing corresponding JSONs to the file e.g.

I must admit that's the part that worries me the more in that bug report. I think we should focus on how to fix that, and then how to fix the endpos processing, if needed. Can you also test with PR https://github.com/dimitri/pgcopydb/pull/151 where the LSN tracking is reviewed entirely and the new code might help, or at least might show a different behavior?
