### ISSUE TITLE
[Feature] Being able to mock data while migrating data

### ISSUE THREAD

**Issue by mhkarimi1383** [dimitri/pgcopydb#165]
Hi
One of the main usages for this tool is for keeping Staging Database Up to data but without real data (for example we want to fake users data)
Is there any solution for that?

**Comment by dimitri** [comment]
The main usage for pgcopydb is to copy a Postgres database from one server to another one. Much like pg_dump and pg_restore, the tool is meant to provide the exact same database definitions and data set.
