### ISSUE TITLE
Schema filtering like pg_dump -n?

### ISSUE THREAD

**Issue by devinshteyn** [dimitri/pgcopydb#167]
Hi,

Is my understanding correct, pgcopydb is supporting database scope operations only, it cannot be filtered down to a single schema?
The usage of --filters isn't very clear from the docs, I couldn't  find any examples, but one sentence description sounded like it can be used to exclude certain tables by their OIDs.

Thanks in advance for answering my question.

**Comment by shubhamdhama** [comment]
@devinshteyn https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_config.html#filtering

**Comment by dimitri** [comment]
Hi @devinshteyn ; we could see about adding `include-only-schema` to our filtering capabilities. Do you want to prepare a PR that implements the feature? I will then review it and help you get to the merge state!

**Comment by dimitri** [comment]
Hi @devinshteyn ; thanks for your efforts implementing the PR, I hope you're allowed to open it and contribute to an Open Source project that your company is using.

About the term “schema”, the technical term for it would be “namespace” as in the `pg_namespace` catalog and all, but it's one of these terms that have an overloaded set of definitions. That's how it is, I believe we have to accept the situation in that case. See also *cluster* as a good example of term overloading in the Postgres docs...
