### ISSUE TITLE
Importing from PostgreSQL 9.3 fails

### ISSUE THREAD

**Issue by ajhsg** [dimitri/pgcopydb#170]
Hi.

I was trying out the 'pgcopydb' program to upgrade an ancient PG 9.3 server to a PG 14 server. The process fails quickly when getting the list of extensions - the output shows the query in schema_list_extensions() in src/schema.c fails with a syntax error at 'with ordinality'. That feature was added in PG 9.4, and the same query also uses 'regnamespace' object identified added in PG 9.5. I tried to rework the query a bit using the 'psql' command line on the 9.3 server via window functions but couldn't get it to work as needed.
I'm hoping that queries used by 'pgcopydb' could be adjusted to work on such an old version, or possible a second block with a 'sql2' variable using syntax accepted by really old PG versions could be added to the routine and called if the first query fails.

Thanks for your work on 'pgcopydb'.

**Comment by ajhsg** [comment]
Hi.

I realize that trying support such an old and unsupported PG release is a big request, and I fully understand as 9.3 has been out of support since 2018 it may be too old to bother with. I've been using 'pg_dump' and 'pg_reload' commands to transfer the data successfully but the index building takes a long time on a few tables. The approach used by 'pgcopydb' looks like a great way to cut way down the potential downtime.

I suggest adding something in the documentation regarding the minimum version of PG that 'pgcopydb' works with if it's not there. If it is there I missed it.

Thanks for your response, and again thank you for working on 'pgcopydb'.

**Comment by dimitri** [comment]
Well we support currently maintained Postgres versions as seen in the `pgcopydb version` output, as in the following example (from a local branch with non-committed changes, but nothing related to the version string). If you manage to get a SQL query that works from 9.3 onwards I will consider implementing it, unless it is significantly more complex than the current query. In the meantime, closing this issue.

```
$ pgcopydb version
13:05:32 55534 INFO   Running pgcopydb version 0.10.18.g721522c.dirty from "/Users/dim/dev/PostgreSQL/pgcopydb/src/bin/pgcopydb/pgcopydb"
pgcopydb version 0.10.18.g721522c.dirty
compiled with PostgreSQL 12.12 on x86_64-apple-darwin16.7.0, compiled by Apple LLVM version 8.1.0 (clang-802.0.42), 64-bit
compatible with Postgres 10, 11, 12, 13, 14, and 15
```
