### ISSUE TITLE
how to deal with extension permission ?

### ISSUE THREAD

**Issue by changchichung** [dimitri/pgcopydb#174]
when I try to run pgcopydb to copy/clone database , always shows "must be the own of extension xxxx" error.
```
09:00:00 1893241 ERROR  pg_restore: error: could not execute query: ERROR:  must be owner of extension cube
09:00:00 1893241 ERROR  Command was: COMMENT ON EXTENSION cube IS 'data type for multidimensional cubes';
09:00:00 1893241 ERROR  Failed to run pg_restore: exit code 1
09:00:00 1893241 ERROR  Failed to clone source database, see above for details
09:00:00 1893239 ERROR  clone process 1893241 has terminated [6]
09:00:00 1893239 WARN   Failed to clone the source database, see above for details
09:00:00 1893239 FATAL  Terminating all processes in our process group
```

I know that promote user account to superuser should solve the issue. but I think it's not a ideal solution.
so is there any suggestion to deal with the extension permission issue  here ?

**Comment by dimitri** [comment]
Hi @changchichung ; please see docs at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_clone.html#postgres-privileges-superuser-and-dump-and-restore where some consideration is given to such a use in details. Consider opening this issue again if you need more information: we will then see about either improving docs and/or fixing bugs if any.
