### ISSUE TITLE
Option to exclude tables

### ISSUE THREAD

**Issue by maxstepanov** [dimitri/pgcopydb#2]
Would be nice to be able to exclude some tables from being copied, like `pg_dump`'s option `--exclude-table-data`

PS. Nice work!

**Comment by dimitri** [comment]
Duplicate of issue #4 ; closing this one here. Please join the discussion on issue #4.

**Comment by dimitri** [comment]
I just merged support for filtering tables at #19 ; and the docs now have a full page for it at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_config.html.
