### ISSUE TITLE
pgcopydb clone --follow crashes with pg_restore

### ISSUE THREAD

**Issue by entrptaher** [dimitri/pgcopydb#217]
Initial clone is successful but after a while, it crashes with pg_restore with following error. 

The DB is very big (takes hours to clone), but I tested it few times by cleaning up the target database, without any success at this stage.

Also, setting `--resume` doesn't prevent it from crashing.

```
11:34:21 3993977 INFO   STEP 3: restore the pre-data section to the target database
11:34:21 3993977 INFO    /usr/bin/pg_restore --dbname 'postgres://postgres@host/db?' --single-transaction --use-list /tmp/pgcopydb/schema/pre.list /tmp/pgcopydb/schema/pre.dump
11:34:21 3993977 ERROR  pg_restore: while PROCESSING TOC:
11:34:21 3993977 ERROR  pg_restore: from TOC entry 1050; 1247 17679 TYPE AlertOptions UsernameHere
11:34:21 3993977 ERROR  pg_restore: error: could not execute query: ERROR:  type "AlertOptions" already exists
11:34:21 3993977 ERROR  Command was: CREATE TYPE public."AlertOptions" AS ENUM (
11:34:21 3993977 ERROR      'PUSH_NOTIFICATION',
11:34:21 3993977 ERROR      'SMS',
11:34:21 3993977 ERROR      'EMAIL',
11:34:21 3993977 ERROR      'DISCORD'
11:34:21 3993977 ERROR  );
11:34:21 3993977 ERROR  Failed to run pg_restore: exit code 1
11:34:21 3993977 ERROR  Failed to clone source database, see above for details
11:34:21 3993975 ERROR  clone process 3993977 has terminated [6]
```

I can confirm the `AlertOptions` indeed exists, but that is because it was cloned by itself just a moment ago. 

Version info:

```
12:04:57 4004654 INFO   Running pgcopydb version 0.11-1.pgdg20.04+1 from "/usr/bin/pgcopydb"
pgcopydb version 0.11-1.pgdg20.04+1
compiled with PostgreSQL 15.2 (Ubuntu 15.2-2.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, 64-bit
compatible with Postgres 10, 11, 12, 13, 14, and 15
```

**Comment by dimitri** [comment]
Hi @entrptaher ; thanks for opening an issue. I see no crash in your output, only a pg_restore error that is handled correctly by pgcopydb. Can you share more of the pgcopydb output/logs please? I can't see why pg_restore would trip on itself that way, so it must be that some other part of the process has already created the "AlertOptions" data type on the target database, or that the type exists already when you start the pgcopydb process.

**Comment by dimitri** [comment]
Closing for triage purposes. Consider opening again with more details if the issue still needs work.
