### ISSUE TITLE
Option to skip VACUUM ANALYSE on target

### ISSUE THREAD

**Issue by shubhamdhama** [dimitri/pgcopydb#226]
VACUUM ANALYSE is a nice thing to have but not essential, it would be great if we can avoid running VACUUM at all. Also, running VACUUM ANALYSE blocks the CREATE INDEX and increases downtime.

**Comment by dimitri** [comment]
See also #228 that fixes the concurrency of VACUUM ANALYZE with respect to the CREATE INDEX activity.
