### ISSUE TITLE
Incorrect SQL query to source DB with jobs=16-20

### ISSUE THREAD

**Issue by aborschev** [dimitri/pgcopydb#239]
Hi! 
With pg_copydb v. 0.10 under high  table-jobs and index-jobs =16-20 we had intermittment (i.e. unstable,  is not reliable reproduced) error:
11:06:50 438030 ERROR [SOURCE] ОШИБКА:  cache lookup failed for attribute 1 of relation 7784126
11:06:50 438030 ERROR SQL query:    select i.oid, n.nspname, i.relname,          r.oid, rn.nspname, r.relname,          indisprimary,          indisunique,          (select string_agg(attname, ',')             from pg_attribute            where attrelid = r.oid              and array[attnum::integer] <@ indkey::integer[]          ) as cols,          pg_get_indexdef(indexrelid),          c.oid,          c.conname,          pg_get_constraintdef(c.oid),          format('%s %s %s',                  regexp_replace(n.nspname, '[
]', ' '),                  regexp_replace(i.relname, '[
]', ' '),                  regexp_replace(auth.rolname, '[
]', ' '))     from pg_index x          join pg_class i ON i.oid = x.indexrelid          join pg_class r ON r.oid = x.indrelid          join pg_namespace n ON n.oid = i.relnamespace          join pg_namespace rn ON rn.oid = r.relnamespace          join pg_roles auth ON auth.oid = i.relowner          left join pg_depend d                  on d.classid = 'pg_class'::regclass                and d.objid = i.oid                and d.refclassid = 'pg_constraint'::regclass                and d.deptype = 'i'          left join pg_constraint c ON c.oid = d.refobjid    where r.relkind = 'r' and r.relpersistence = 'p'       and n.nspname !~ '^pg_' and n.nspname <> 'information_schema'      and rn.nspname = $1 and r.relname = $2 order by n.nspname, r.relname
11:06:50 438030 ERROR SQL params: 'nsi', 'as_addr_obj'
11:06:50 438030 ERROR Failed to list all indexes for table "nsi"."as_addr_obj"
11:06:50 438030 WARN  Failed to create all the indexes for "nsi"."as_addr_obj", see above for details

The SQL query to Source DB was: 
select i.oid, 
    n.nspname, 
    i.relname,
    r.oid, 
    rn.nspname, 
    r.relname,          
    indisprimary,          
    indisunique,          
    (select string_agg(attname, ',')
    from pg_attribute
    where attrelid = r.oid
    and array[attnum::integer] <@ indkey::integer[]
    ) as cols,
    pg_get_indexdef(indexrelid),
    c.oid,
    c.conname,
    pg_get_constraintdef(c.oid),
     regexp_replace(n.nspname,  '[zz]', ' '),
   format('%s %s %s', regexp_replace(n.nspname,  '[]', ' '), regexp_replace(i.relname, '[]', ' '),  regexp_replace(auth.rolname, '[]', ' '))     
from pg_index x
join pg_class i ON i.oid = x.indexrelid
join pg_class r ON r.oid = x.indrelid
join pg_namespace n ON n.oid = i.relnamespace
join pg_namespace rn ON rn.oid = r.relnamespace
join pg_roles auth ON auth.oid = i.relowner
left join pg_depend d
on d.classid = 'pg_class'::regclass
and d.objid = i.oid
and d.refclassid = 'pg_constraint'::regclass
and d.deptype = 'i'
left join pg_constraint c ON c.oid = d.refobjid
where r.relkind = 'r' and r.relpersistence = 'p'
    and n.nspname !~ '^pg_' and n.nspname <> 'information_schema'
    and rn.nspname = 'public' and r.relname = 'as_addr_obj' 
order by n.nspname, r.relname;

The exact error place is:
 regexp_replace(n.nspname,  '[]', ' ')
SQL Error [2201B]: ERROR: invalid regular expression: brackets [] not balanced
- For some reason, regexp in [] does not get populated. 

Additional info:
- When we re-run pg_copydb, this error may appear on other tables.
- When run with --table-jobs and -- index-jobs  = 4 or 8, this error does not appear and DB copy goes fine.
- Pg_copydb was installed on target DB server, Alt Linux 8.2, 32 CPUs - i.e. it does not looks as CPU contention.

**Comment by dimitri** [comment]
The attached PR might fix this bug, please build from current sources and try again, then report if that's good or re-open the issue if more work is needed!
