### ISSUE TITLE
Proposal: Pg_copydb + vanilla logical replication

### ISSUE THREAD

**Issue by aborschev** [dimitri/pgcopydb#240]
Hi, colleagues!
Currently pg_copydb does "manual logical replication" - i.e. create logical replication slot, get transaction info as json (or text with test plugin), creates files on disk, converts them to SQL and applyes them to target DB.
This approach hav Pro's: works with PG 9.6, better control on DB apply operation.
And contra's:  complex JSON -> SQL conversion,  reqieres space on discs for .json and .sql files.

The idea is:  to implement new pg_copydb mode, where pg_copydb uses standard logical replication mechanics. 
Approximate steps would be:
1) pgcopydb  gets dictionary from source - as usual.
2) on source DB:
  CREATE PUBLICATION 'pgcopydb_pub' FOR ALL TABLES (or maybe it is better to luist tales to support include/exclude filters)
3) on source DB we start transaction: 
BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT pg_export_snapshot();
and create logical replication slot:
pg_create_logical_replication_slot('pgcopydb_slot', ...)
From this moment source DB starts to accumulate WALs needed for replay.
4) Start data transfer using exported snapshot id. 
5) COMMIT  - I am not sure, can we do this when COPY is started, or wait until end of data transfer.

6) Maybe, update sentinel table here?

7) When data copy is completed, pgcopydb creates subscription:
CREATE SUBSCRIPTION pgcpoydb_sub
         CONNECTION 'host=source_host port=5432 user=foo dbname=foodb'   -- maybe, URI format postgresql://... is supported here?
        PUBLICATION pgcopydb_pub
               WITH (slot_name = 'pgcopydb_slot',
                           create_slot = false,
                           copy_data = false,  
                           enabled = true);  

7) PG start to transfer data since slot creation via logical replication.

8) pgcopydb starts monitoring of logical reloication - watcing on souce and target LSNs in pg_replication_slots

9) On  pgcopydb stream sentinel set endpos --current  :
- we stop logical replication, wait until data transfer compltes, 
- transfer sequences

10 ) At last, we do cleanup - as pgcopydb  already does + drop publication

What is Your opinion:
- Should this approach work, if any steps are wrong or missing?
- Is this difficult to implement?
- If there any objections, comments or ideas?

**Comment by dimitri** [comment]
Hi @aborschev ; thanks for you suggestion! Using logical replication in Postgres still comes with a couple of trade-offs that were not seen as favorable to pgcopydb. Specifically, both CREATE PUBLICATION and CREATE SUBSCRIPTION are superuser-only commands. 

Then, in many High Velocity environments we need to be able to prefetch database changes during the initial COPY of the database, as a way to avoid too much pressure on the source database instance in terms of volume of WAL files to keep around.

When dealing with a multi-TB database that's pretty active, if the initial copy lasts for a couple days, it's best to avoid asking the source dartabase instance to keep two days worth of WAL content on the production disk. When that disk is full, your production instance just stops. 

That is the trade-off that has been implemented in pgcopydb at the moment and the reason why logical decoding was prefered over built-in logical replication, despite it being very manual as you mention.

If you have a way to overcome these limitations when using logical replication, then let's see the design, we might be able to implement support for both approaches.

**Comment by aborschev** [comment]
This data  are about "cold" copying,  i.e.  no follow,  no workload on source.

 pgcopydb clone 
--roles 
--table-jobs=4 
--index-jobs=4 
--source postgres://<username>:<password>@astralinux:5432/database1 
--target postgres://<username>:<password>@altlinux:5432/database2

**Comment by dimitri** [comment]
Duplicate with #387. Closing this one for triage. (We're considering it, it will probably happen).
