### ISSUE TITLE
exclude filter  does not work for  views

### ISSUE THREAD

**Issue by plvnv** [dimitri/pgcopydb#250]
Hi, it looks like the exclude_table filter  section does not work for views

create filter configuration pgcopy.filter

```
[exclude-table]
"public"."test_view"
```

then clone database test_db with 2 objects test_table and test_view 

`pgcopydb clone --trace --filters pgcopy.filter`

 trace output

```
.....
20:23:38 408 DEBUG  filtering.c:167           Sections "exclude-schema" not found
20:23:38 408 DEBUG  filtering.c:179           Section "exclude-table" has 1 entries
20:23:38 408 TRACE  filtering.c:241           exclude-table "public"."test_view"
20:23:38 408 DEBUG  filtering.c:167           Sections "exclude-table-data" not found
20:23:38 408 DEBUG  filtering.c:167           Sections "exclude-index" not found
20:23:38 408 DEBUG  filtering.c:167           Sections "include-only-table" not found
.....
```

after job done in destination database

psql (13.10)
Type "help" for help.

```
postgres=# \c test_db 
You are now connected to database "test_db" as user "postgres".
test_db=# \dv
          List of relations
 Schema |   Name    | Type |  Owner   
--------+-----------+------+----------
 public | test_view | view | postgres
(1 row)

```

pgcopydb version:

```
pgcopydb --version
20:43:17 24087 INFO   Running pgcopydb version 0.11.26.gf05d75b from "/opt/pgpro/std-11/bin/pgcopydb"
pgcopydb version 0.11.26.gf05d75b
compiled with PostgreSQL 11.15 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit
compatible with Postgres 10, 11, 12, 13, 14, and 15
```

**Comment by dimitri** [comment]
Yeah well the name of the filter is `exclude-table`, right?

What happens is that pgcopydb enhances using pg_dump and pg_restore in the context of copying a database from a source Postgres instance that's currently available to a target Postgres instance (also available). To do so pgcopydb uses pg_dump and pg_restore as-is for the schema parts of the operations, pre-data and post-data, and implements its own way to handle the data parts.

The filtering feature of pgcopydb is meant for the pgcopydb internal operations, so it is meant to take care of table list, ability to skip some of the table data, and then indexes and other objects that depend on tables. Then schema are supported to make it easy to exclude all the tables in a specific schema at once.

There is no provision to handle other kind of objects at this point.

The easiest way for you to skip a view is to either drop the view from the source database before running pgcopydb, or drop the view from the target database after running pgcopybd.
