### ISSUE TITLE
Fail fast for online mode too

### ISSUE THREAD

**Issue by shubhamdhama** [dimitri/pgcopydb#256]
For some reason, if any of the online mode sub-processes (apply, transform, catch-up) isn't able to recover from failures, for example, an error in transforming the message or an error while applying the message, we should fail the migration.
Similar to #222

**Comment by dimitri** [comment]
Given the following piece of code, I believe we already exit early the follow sub-processes as soon as one of them fails. What happens then is that we try the other mode of replay (switching between pre-fetch and catchup to live replay in a loop). We don't have a provision for non-retryable errors.

https://github.com/dimitri/pgcopydb/blob/main/src/bin/pgcopydb/follow.c#L754-L777

**Comment by shubhamdhama** [comment]
I recall this was fixed. Thanks @dimitri
