### ISSUE TITLE
pgcopydb copy schema implements both pre-data and post-data sections

### ISSUE THREAD

**Issue by thecatontheflat** [dimitri/pgcopydb#269]
I noticed that after running `pgcopydb copy schema` the target DB received all the indexes and constraints. I guess it's a bug?

**Comment by dimitri** [comment]
It's not a bug. The docs at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_copy.html#pgcopydb-copy-schema could be more specific about it though. If you want more control, consider using `pgcopydb dump schema` and then `pgcopydb restore pre-data` and `pgcopydb restore post-data` separately.

**Comment by thecatontheflat** [comment]
Oh, I must have misunderstood the docs, sorry about that!

I've also worked around it by Ctrl+C when it gets to restoring the PKs and indexes step :D
