### ISSUE TITLE
pgcopydb not using the column names while copying data

### ISSUE THREAD

**Issue by PurnaChandraRaoK** [dimitri/pgcopydb#275]
pg_dump is using command like this to copy data from source database table

**COPY public.part_config (parent_table, control, partition_type, partition_interval, constraint_cols, premake, optimize_trigger, optimize_constraint, epoch, inherit_fk, retention, retention_schema, retention_keep_table, retention_keep_index, infinite_time_partitions, datetime_string, use_run_maintenance, jobmon, sub_partition_set_full, undo_in_progress, trigger_exception_handling, upsert, trigger_return_null) FROM stdin;**

pgcopydb is performing like this 

**copy (SELECT * FROM "public"."part_config" ) to stdout;
copy "public"."part_config" from stdin;
COPY part_config, line 1: "public.time_taptest_table        col3   native   1 day   \N      4       4       30      none    t       \N      \N      t       t       f       YYYY_MM_DD     on       t       f       f       f               t       pu..."
missing data for column "inherit_privileges"
TARGET Context: Failed to copy data to target**

Because of this if there are any newly added columns to that table that are having default value they are not getting copied and giving error like
**missing data for column "inherit_privileges"
TARGET Context: Failed to copy data to target**

More logs can be found here [partman.txt](https://github.com/dimitri/pgcopydb/files/11381571/partman.txt)

**Comment by thecatontheflat** [comment]
I would love if there was support for column names, too. Our use case is that we often clone the database when altering tables or upgrading to a newer version. In case of a schema change, using pgcopydb becomes difficult

**Comment by thecatontheflat** [comment]
I started getting the following error when running `copy table-data`:

```
16:23:08 571 ERROR  SOURCE [42703] ERROR:  column "........pg.dropped.3........" does not exist                                                 
16:23:08 571 ERROR  SOURCE LINE 1: copy (SELECT "id", "data_source", "........pg.dropped.3........                                              
16:23:08 571 ERROR  SOURCE                                           ^                                                                          
16:23:08 571 ERROR  SOURCE Context: 5eU 
```

I used `pg_dump` and `pg_restore` to duplicate the schema from Source to Target. The fields are identical, have the same order, but their "position index" is different (in the Target table, after `pg_restore`, the column position indexes don't have a sequence gap). I wonder if that could be an issue?

**Comment by thecatontheflat** [comment]
Indeed, when I run it with debug, it generates the following statement:
```
17:54:09 81 NOTICE table-data.c:852          COPY "public"."my_table"("id", "my_field_b", "........pg.dropped.3........", "........pg.dropped.4........", "my_field_c")
```

**Comment by thecatontheflat** [comment]
Steps to reproduce:

1. Create a table with 3 fields
2. Alter table drop field 2
3. Alter table add another field
4. Use pg_dump / pg_restore to dump the schema
5. Run `copy table-data`

**Comment by thecatontheflat** [comment]
I think the `from pg_attribute` queries are missing `WHERE attisdropped = FALSE` condition
