### ISSUE TITLE
Can it be deployed on CentOS/RedHat?

### ISSUE THREAD

**Issue by EarnestHyman** [dimitri/pgcopydb#286]
Can it be deployed on CentOS/RedHat?

**Comment by dimitri** [comment]
Yes. That said the Postgres community packagers for RPM based system didn't work their magic yet. I have now opened a ticket on their system at https://redmine.postgresql.org/issues/7820. See https://yum.postgresql.org/ for more information about this initiative and how to then install the packages once they are made available.

**Comment by devrimgunduz** [comment]
It is already available via our community repository:

https://yum.postgresql.org/

I'll just need to update to 0.11.

Regards, Devrim

**Comment by dimitri** [comment]
Thanks for the feedback @devrimgunduz ! when browsing in places such as https://download.postgresql.org/pub/repos/yum/common/redhat/rhel-8-x86_64/ to list available packages, I failed to see pgcopydb in that list.

I just tried playing with an RPM distribution in a docker container (`docker run --rm -it rockylinux:9`) and finally could run `dnf install -y pgcopydb_15`. Why is the package name not just `pgcopydb`? where is that documented? 

``` 
[root@74897e72ca3d /]# dnf search postgresql15-server
Last metadata expiration check: 0:00:53 ago on Mon May 22 09:21:10 2023.
===================================================== Name Exactly Matched: postgresql15-server ======================================================
postgresql15-server.x86_64 : The programs needed to create and run a PostgreSQL server
[root@74897e72ca3d /]# dnf search pgcopydb
Last metadata expiration check: 0:00:58 ago on Mon May 22 09:21:10 2023.
=============================================================== Name Matched: pgcopydb ===============================================================
pgcopydb_11.x86_64 : Automate pg_dump | pg_restore between two running Postgres servers
pgcopydb_12.x86_64 : Automate pg_dump | pg_restore between two running Postgres servers
pgcopydb_13.x86_64 : Automate pg_dump | pg_restore between two running Postgres servers
pgcopydb_14.x86_64 : Automate pg_dump | pg_restore between two running Postgres servers
pgcopydb_15.x86_64 : Automate pg_dump | pg_restore between two running Postgres servers
```

**Comment by devrimgunduz** [comment]
Hi @dimitri ,

The way PGDG *RPMs* are packaged requires pgcopydb to be dependent on PG versions. pgcopydb requires common/fe_memutils.h, which is not included in our common libpq5-devel package, but included in postgresql1X-devel package. Thus, it is dependent on each PG version.

**Comment by dimitri** [comment]
Hi @devrimgunduz ; thanks for following-up with the question, I appreciate it! Is there a way that we can fix that? In debian (see https://packages.debian.org/sid/pgcopydb) we don't have that problem after all... is it possible that this is a build-time dependency, not a run-time thing? The user won't care what version of Postgres was used to build the tool, this has no impact on how you use it or its compatibility with Postgres versions etc.
