### ISSUE TITLE
Error relation "pgcopydb_table_size" does not exist, after another error

### ISSUE THREAD

**Issue by lospejos** [dimitri/pgcopydb#288]
There is an error using `pgcopydb` for data migration, when there're tables with triggers/trigger functions, which update/create new data in another tables after changing data in source table.

Consider example.

1) **Source** database is `PostgreSQL 10.23` installed locally on port `5432`;
2) **Target** database is `PostgreSQL 15.2` installed locally on port 5435;
3) Source database schema definition is attached in file [source_db_1.sql.txt](https://github.com/dimitri/pgcopydb/files/11470446/source_db_1.sql.txt). Please note, in this schema there is a table `tbl1`, which has a trigger attached (after row update): on certain conditions trigger function inserts a brand new row into another table `tbl2`!;
4) Filter file was applied, see file file [pgcopydb_filter.txt](https://github.com/dimitri/pgcopydb/files/11470454/pgcopydb_filter.txt);
5) Cloned git repository (`main` branch, `git log` shows last commit as `19f72f6 2023-05-11`);
6) Modified `src\bin\pgcopydb\schema.c` file, because without these changes another error appears preventing further execution, see related issues: #276 and #280 ;
6.1) all occurrences of 
`"        and d.deptype in ('i', 'a') "`
was replaced with
`"        and d.deptype in ('i'/*, 'a'*/) "` 
6.2) all occurrences of
`"        and at.attnum = a.adnum "`
was replaced with
`"        and at.attnum = a.adnum and false "`
This prevents sequences exclusion. _I know that this is a kind of a dirty hack, but these are temporary changes to allow further processing_.
7) Executable built and started: `clone --follow --table-jobs 4 --index-jobs 4 --restart --no-acl --no-owner --no-role-passwords --fail-fast --filter /opt/pgcopydb_filter.txt --trace` ;
8) The initial data load was successful, no errors appeared and logical replication was started;
9) After inserting row `insert into tbl1 (desc_text) values ('rec1') returning *;` in source database into the table `tbl1`, this row successfully replicated into target table;
10) When we do update data in source database in table `tbl1` (which has trigger) `update tbl1 set status_id = 2 where id = 1;` an error appears and replication fails: `ERROR:  relation "pgcopydb_table_size" does not exist`. But earlier in logs there is another error: `Failed to find old-key in UPDATE message: table s1.tbl1: UPDATE: id[bigint]:1 status_id[bigint]:2 desc_text[character varying]:'rec1'`.

For your convenience I've attached full logs and files here: 
[local_db_test_2023-05-13.zip](https://github.com/dimitri/pgcopydb/files/11470463/local_db_test_2023-05-13.zip)

I'm not sure is this a `pgcopydb` issue or something else. I suppose that root cause is the data changing in target database independently from data migration processes, this data changed by a trigger / trigger function.

For now I don't see any workaround except disabling all triggers that may change data independently from replication process on target database until logical replication ends (until `cutoff stage`).

Probably another option would be adding some checks on replication start: if there some triggers exists and enabled on target database, put some warning or error or something like this.

**Comment by lospejos** [comment]
The `pg_restore` tool has command line argument: `--disable-triggers`. Probably the possible solution would also creating the correspondent argument for `pgcopydb` and pass/use this value when restoring.

See https://www.postgresql.org/docs/current/app-pgrestore.html

**Comment by dimitri** [comment]
The OLD-KEY error is because we're still lacking some support for test_decoding in pgcopydb, please use wal2json at the time being. See https://github.com/dimitri/pgcopydb/issues/241 for more details. I think the error about pgcopydb_table_size is a separate error, I will try to find some time and read the logs you provided. Maybe you can select relevant extracts of them here in the meantime?

**Comment by lospejos** [comment]
Thanks for a quick response.
I've updated my example to use `wal2json` replication plugin, used it when starting pgcopydb:
```
$ pgcopydb ... clone --follow --plugin wal2json
```

The error changed, it's now:
```
2023-05-15 18:39:27 4135 SQL    pgsql.c:1508              [TARGET] UPDATE "s1"."tbl1" SET "id" = 1, "status_id" = 2, "desc_text" = 'rec1' WHERE "id" = 1;
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1892              Postgres result status is PGRES_FATAL_ERROR
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET] ERROR:  relation "tbl2" does not exist
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET] LINE 1: insert into tbl2(
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET]                     ^
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET] QUERY:  insert into tbl2(
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET]             tbl1_id, desc_text
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET]         ) values (
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET]             NEW.id,
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET]             right(concat('from trf @', (now() at time zone 'utc'), 'Z'), 32)
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET]         )
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1543              [TARGET] CONTEXT:  PL/pgSQL function s1.trf_tbl1_status_changed() line 8 at SQL statement
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1548              SQL query: UPDATE "s1"."tbl1" SET "id" = 1, "status_id" = 2, "desc_text" = 'rec1' WHERE "id" = 1
2023-05-15 18:39:27 4135 ERROR  pgsql.c:1549              SQL params: 
2023-05-15 18:39:27 4135 ERROR  ld_replay.c:132           Failed to transform JSON messages from input stream, see above for details
```

Please note that this SQL statement `insert into tbl2...` is the trigger function SQL statement which works fine on source database `db_1`;

After that it complains for `ERROR:  relation "pgcopydb_table_size" does not exist` (you mentioned above that you think that `the error about pgcopydb_table_size is a separate error`).

Please note, that tables `tbl_1` , `tbl_2`, trigger function `trf_tbl1_status_changed` are present in custom schema `s1`, not in default `public` schema. I suppose this may be the issue. Somehow somewhere the `set search_path=s1` should be executed.

**Comment by lospejos** [comment]
I've tried another test after `pgcopydb` was updated.

1) Pulled last changes in `main` branch up to commit `b2e69c1`
2) Made changes to disable sequences filtering to prevent errors, see #276 #280 
3) Built `pgcopydb`, prepared source and target databases
4) Started `pgcopydb clone --follow --table-jobs 4 --index-jobs 4 --restart --no-acl --no-owner --no-role-passwords --fail-fast --filter /opt/pgcopydb_vanilla_filter.ini --plugin wal2json --trace`
5) After initial data load was completed, but **before starting changing data** in `source` database, I also **disabled trigger** in `target` database;
6) Changed data in `source` database, all data successfully migrated to a `target` database, replication process not crashed like before.

In this develop local target database I disabled one test trigger manually. However, there are probably another approaches to get this, because in a production environment:
- we cannot prevent data changing before we disable all triggers manually;
- it could be difficult to catch the moment for manual disabling all triggers.

F.e. connections to target database could execute `SET session_replication_role = replica;` on each connection to target database at least on logical replication stage until `cutoff` moment happens. And during `cutoff` restore it using `SET session_replication_role = DEFAULT;`. I just suppose that and I'm not sure is it correct or not.

**Comment by plvnv** [comment]
Good afternoon colleagues, is there any news on this problem?

**Comment by dimitri** [comment]
Hi @lospejos ; can you please try building a local version of pgcopydb with the PR #308 (branch fix/session-replication-role-replica) applied and report your findings? it should allow skipping triggers double-evaluation by setting the GUC `session-replication-role` to `replica` in the context of the apply process.

**Comment by lospejos** [comment]
@dimitri 

Updated repository, checkout out branch `fix/session-replication-role-replica`.
Built `pgcopydb` binary.
After starting on the same databases (tables have sequences and trigger functions):
```bash
# pgcopydb clone --follow --table-jobs 4 --index-jobs 4 --restart --no-acl --no-owner --no-role-passwords --fail-fast --filter /opt/pgcopydb_filter.ini
```
Error appeared:
```
2023-06-06 14:44:49 9208 ERROR  pgsql.c:1892              Postgres result status is PGRES_FATAL_ERROR
2023-06-06 14:44:49 9208 ERROR  pgsql.c:1543              [TARGET] ERROR:  relation "s1.tbl1_id_seq" does not exist
2023-06-06 14:44:49 9208 ERROR  pgsql.c:1548              SQL query: select pg_catalog.setval(format('%I.%I', $1, $2), $3, $4)
2023-06-06 14:44:49 9208 ERROR  pgsql.c:1549              SQL params: 's1', 'tbl1_id_seq', '1', 'true'
2023-06-06 14:44:49 9208 ERROR  schema.c:2047             Failed to set sequence "s1"."tbl1_id_seq" last value to 1
2023-06-06 14:44:49 9208 ERROR  sequences.c:211           Failed to set sequence values for "s1"."tbl1_id_seq"
```
This error may be related to:

https://github.com/dimitri/pgcopydb/issues/280

https://github.com/dimitri/pgcopydb/issues/310

I'll try to patch `schema.c` (disable sequences exclusion, unfortunately, without this patch I cannot continue testing due to error described above) and will share the results later here.

**Comment by dimitri** [comment]
It seems to me that somewhere else you are telling the issue you have here is because of the filtering. In the context of validating PR #308 please try without using any filtering? One thing at a time, you know...

**Comment by lospejos** [comment]
@dimitri Also I hope you didn't forgot to restore `session-replication-role` from `replica` to `default` (or what it should be) on `cutoff` stage or somewhere.

**Comment by lospejos** [comment]
> In the context of validating PR #308 please try without using any filtering?

@dimitri 
OK, I'll try to test it without filtering and share results here soon.

**Comment by lospejos** [comment]
> In the context of validating PR #308 please try without using any filtering?

@dimitri Without using filtering features this error also not appears, everything works as expected (using patched `schema.c`, see above).

**Comment by dimitri** [comment]
Okay I merged the session_replication_role changes. FYI Postgres GUCs can be set within the context of a session or a transaction too via using the SET command. That's what we're doing here, and it means we don't have to change anything when the migration cutover happens.
