### ISSUE TITLE
online: Missing `commit_lsn` when transaction spans over multiple files

### ISSUE THREAD

**Issue by shubhamdhama** [dimitri/pgcopydb#299]
Follow up of https://github.com/dimitri/pgcopydb/pull/295#issuecomment-1560554295

Here the issue is that transform process doesn't have knowledge of anything beyond current file. So if COMMIT LSN lies in next file we won't be able to put it in BEGIN statement as required by apply process.
```
2023-05-26 10:46:18 44677 FATAL  ld_apply.c:503            Failed to parse BEGIN message: BEGIN; -- {"xid":225878,"lsn":"35/7D1E5958","timestamp":"2023-05-26 05:15:31.624392+0530","commit_lsn":"0/0"}
```

**Proposal**

In transform process, we should write partial transactions's JSONs and skip writing transformed content to SQL 
https://github.com/dimitri/pgcopydb/blob/a68032a5fcc32ff2fb03640c5c79b08cbba5d637/src/bin/pgcopydb/ld_transform.c#L849-L860

e.g.
Say we have few transactions in `00000001000000350000007F.json` which are incomplete, so skip writing them to `00000001000000350000007F.sql`, instead write their JSON messages (or we can write SQL too if we want to avoid re-processing) to `000000010000003500000080.pre.json`.
And when we start transforming `000000010000003500000080.json`, first transform messages in `000000010000003500000080.pre.json` followed by `000000010000003500000080.json`

This should work even when single transaction may span over more than two files.

**Comment by dimitri** [comment]
If I rewrite your Problem Statement as follows: 

> we need the commit_lsn in the BEGIN message in the SQL file so that we know if we have to apply the transaction or not, but because we process one JSON file at a time we do not have the information in transactions that spans multiple JSON files.

The thing we know is the transaction XID. So when a transaction spans multiple files, let's write a xid.json file with the information we have, and complete the file when we process the COMMIT message later (rewrite the file with the full information). The file is only one line, JSON, with the transaction metadata. Lookup is easy: XID.json. Cleanup is easy: once the replay has committed, delete the file.

With the original scenario:

```
Failed to parse BEGIN message: BEGIN; -- {"xid":225878,"lsn":"35/7D1E5958","timestamp":"2023-05-26 05:15:31.624392+0530","commit_lsn":"0/0"}
```

When writing the BEGIN message, skip the commit_lsnmetadata, instead write a new file `225878.json` with the contents:

``` json
{"xid":225878,"lsn":"35/7D1E5958","timestamp":"2023-05-26 05:15:31.624392+0530"}
```

and later when you read the COMMIT message for that transaction, if the XID file exists, open it, check it has the same metadata as you have, and rewrite it with the `commit_lsn` that we now have.

In the apply process, when we have a transaction without the commit_lsn, try and read the XID file for it. If it contains the commit lsn, all is good. If not, busy loop reading it until it has the information.
