### ISSUE TITLE
Problem with the connection string with escape characters

### ISSUE THREAD

**Issue by pjknkda** [dimitri/pgcopydb#31]
When connection string contains escape characters, commands fails because these characters are passed to `pg_dump` or `pg_restore` with being unescaped. More precisely,
- `pg_dump_db` or `pg_restore_db` use `safeURI.pguri` from `extract_connection_string_password`
- `extract_connection_string_password` builds `safeURI.pguri` using `buildPostgresURIfromPieces`
- `buildPostgresURIfromPieces` reconstructs connection string using `uriParams` which is created from `parse_pguri_info_key_vals`
- `parse_pguri_info_key_vals` builds `uriParameters` using `PQconninfoOption` which is created from `PQconninfoParse`
- `PQconninfoParse` returns unescaped string

For example, PostgreSQL served by Azure enforces to contain "@" character in username to represent Azure's account name, and therefore escaping for "@" should be used, 

```
export PGCOPYDB_SOURCE_PGURI="postgres://test%40myaccount:password@myaccount.postgres.database.azure.com/mydb"
export PGCOPYDB_TARGET_PGURI="postgres://test%40myaccount2:password@myaccount2.postgres.database.azure.com/mydb"

$ pgcopydb copy-db
14:59:55 79 INFO  [SOURCE] Copying database from "postgres://test@myaccount@myaccount.postgres.database.azure.com:/mydb?password=****"
14:59:55 79 INFO  [TARGET] Copying database into "postgres://test@myaccount2@myaccount2.postgres.database.azure.com:/mydb?password=****"
14:59:55 79 INFO  Using work dir "/tmp"
14:59:55 79 INFO  STEP 1: dump the source database schema (pre/post data)
14:59:56 79 INFO  Exported snapshot "00000085-00058CC6-1" from the source database
14:59:56 79 INFO   /usr/bin/pg_dump -Fc --snapshot 00000085-00058CC6-1 --section pre-data --file /tmp/schema/pre.dump 'postgres://test@myaccount@myaccount.postgres.database.azure.com:/mydb?'
14:59:56 79 ERROR pg_dump: error: connection to database "mydb" failed: could not translate host name "myaccount@myaccount.postgres.database.azure.com" to address: Name or service not known
14:59:56 79 ERROR Failed to run pg_dump: exit code 1

```

**Comment by dimitri** [comment]
Hi @pjknkda ; thanks for the bug report. I believe the bug should now be fixed in linked PR. Is it possible for you to test it and report back?

**Comment by pjknkda** [comment]
It works perfectly. Thank you!
