### ISSUE TITLE
Cant copy to Azure Flex server

### ISSUE THREAD

**Issue by koffein71** [dimitri/pgcopydb#316]
Hi,
i have some trouble to copy database to Azure Flex Server.

```
/# pgcopydb --version
13:33:11 7745 INFO   Running pgcopydb version 0.11 from "/usr/local/bin/pgcopydb"
pgcopydb version 0.11
compiled with PostgreSQL 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit
compatible with Postgres 10, 11, 12, 13, 14, and 15
```

Source database is postgres10, target db a Azure Flex Server version 14.8

pgcopydb tries to copy roles with superuser attribute especially 'postgres' to the Azure target which fails due to missing superuser attribute for that user uesd by pgcopydb.
The only user with superuser role in target db is a azuresu user created by Azure for management purpose for its own use. Obviously it's not possible to create other users with superuser role there.

Is there a way to solve this problem ?
Thanks in advance.

**Comment by lospejos** [comment]
You could create required users manually before migration, and call data migration like

```
pgcopydb --no-acl --no-owner --no-role-passwords <other options>
```


to prevent roles creation on target database.

**Comment by dimitri** [comment]
See also https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_copy.html#pgcopydb-copy-roles

**Comment by koffein71** [comment]
Works. Thanks for hint.
