### ISSUE TITLE
Mismatch pgdump version with PostgreSQL server version

### ISSUE THREAD

**Issue by qguang** [dimitri/pgcopydb#322]
I am testing pgcopydb. The source and target database cluster are version 14.8 and I am using dpage/pgadmin4 latest.
I ran into the error below.

02:37:29 367 INFO   STEP 1: dump the source database schema (pre/post data)
02:37:29 367 INFO    /usr/bin/pg_dump -Fc --snapshot 00000007-000000AD-1 --section pre-data --file /tmp/pgcopydb/schema/pre.dump 'postgres://postgres@local-postgres-14-source:5432/crm_database?'
02:37:29 367 ERROR  pg_dump:
02:37:29 367 ERROR   error: server version: 14.8 (Debian 14.8-1.pgdg110+1); pg_dump version: 13.11 (Debian 13.11-0+deb11u1)
02:37:29 367 ERROR  pg_dump: error:
02:37:29 367 ERROR  aborting because of server version mismatch
02:37:29 367 ERROR  Failed to run pg_dump: exit code 1
02:37:29 367 ERROR  Failed to clone source database, see above for details
02:37:29 342 ERROR  clone process 367 has terminated [6]

**Comment by dimitri** [comment]
Fix your PATH so that the `pg_dump` binary that is found first is the proper one.
