### ISSUE TITLE
tiger_data schema already exists error when tried migration using pgcopydb with postgis_tiger_geocoder extension installed

### ISSUE THREAD

**Issue by PurnaChandraRaoK** [dimitri/pgcopydb#327]
Error:

2023-06-19 10:36:34 31 ERROR  string_utils.c:603        pg_restore: [archiver (db)] Error while PROCESSING TOC:
2023-06-19 10:36:34 31 ERROR  string_utils.c:603        pg_restore: [archiver (db)] Error from TOC entry 14; 2615 154121 SCHEMA tiger_data postgres
2023-06-19 10:36:34 31 ERROR  string_utils.c:603        **pg_restore: [archiver (db)] could not execute query: ERROR:  schema "tiger_data" already exists**
2023-06-19 10:36:34 31 ERROR  string_utils.c:603            **Command was: CREATE SCHEMA tiger_data;**
2023-06-19 10:36:34 31 ERROR  pgcmd.c:867               Failed to run pg_restore: exit code 1
2023-06-19 10:36:34 31 ERROR  cli_clone_follow.c:433    Failed to clone source database, see above for details

</BODY></HTML>

Steps to reproduce:

1) Execute this query **create extension postgis_tiger_geocoder cascade;** on source server database 
2) pgcopydb clone --skip-extensions --no-owner --no-acl --table-jobs 8 --index-jobs 2 -vvv

On installing postgis_tiger_geocoder extension it will create two schemas tiger, tiger_data

If we don't use --skip-extensions in step2 while reproducing we will hit this error

Error:

16:28:54 404 ERROR  string_utils.c:603: pg_restore: while PROCESSING TOC:
16:28:54 404 ERROR  string_utils.c:603: pg_restore: from TOC entry 13; 2615 153840 SCHEMA tiger postgres
**16:28:54 404 ERROR  string_utils.c:603: pg_restore: error: could not execute query: ERROR:  schema "tiger" already exists
16:28:54 404 ERROR  string_utils.c:603: Command was: CREATE SCHEMA tiger;**
16:28:54 404 ERROR  pgcmd.c:792: Failed to run pg_restore: exit code 1
16:28:54 404 ERROR  cli_clone_follow.c:390: Failed to clone source database, see above for details
16:28:54 401 ERROR  cli_clone_follow.c:675: clone process 404 has terminated [6]

**Comment by dimitri** [comment]
The error with the schema already existing is now fixed. That said, we still need superuser when running `pg_dump` and an extension has created data in a schema:

``` 
10:07:53 102 INFO   STEP 2: dump the source database schema (pre/post data)
10:07:53 102 INFO    /usr/bin/pg_dump -Fc --snapshot 00000003-00000024-1 --section pre-data --exclude-schema tiger --file /tmp/pgcopydb/schema/pre.dump postgres://pagila@source/pagila
10:07:54 102 ERROR  pg_dump: error: query failed: ERROR:  permission denied for schema tiger
10:07:54 102 ERROR  pg_dump: error: query was: LOCK TABLE tiger.geocode_settings IN ACCESS SHARE MODE
10:07:54 102 ERROR  Failed to run pg_dump: exit code 1
10:07:54 102 ERROR  Failed to clone source database, see above for details
```

That's because `pg_dump` does not know how to respect the `--exclude-schema` instruction when the schema contains elements that belong to an extension.
