### ISSUE TITLE
How to correctly resume logical replicatoin after failure

### ISSUE THREAD

**Issue by lospejos** [dimitri/pgcopydb#374]
I have successfully set up and started initial and logical replication using `pgcopydb ... clone --follow...` command.

After some time, the target database server become unavailable (network issues) and logical replication stopper with errors in logs:

```
Connection to database failed: connection to server at "psql-dev" (x.x.x.x), port 5432 failed: timeout expired
```

I would like to resume this replication.

I've tried:

1) `pgcopydb follow ... --resume ...`

Error:
```
ERROR  cli_common.c:450          Options --snapshot is mandatory unless using --not-consistent
FATAL  cli_common.c:1098         Option --resume requires option --not-consistent
```
2) `pgcopydb follow ... --resume --not-consistent`

Error:
```
ERROR  pgsql.c:3460              Failed to send CREATE_REPLICATION_SLOT command:
ERROR  pgsql.c:2474              SOURCE [42710] ERROR:  replication slot "pgcopydb" already exists
ERROR  pgsql.c:2482              SOURCE Context: CREATE_REPLICATION_SLOT "pgcopydb" LOGICAL "wal2json"
ERROR  snapshot.c:404            Failed to create a logical replication slot and export a snapshot, see above for details
```

3) `pgcopydb follow ... --resume --not-consistent --slot-name pgcopydb ...`

Error:

```
ERROR  pgsql.c:3460              Failed to send CREATE_REPLICATION_SLOT command:
ERROR  pgsql.c:2474              SOURCE [42710] ERROR:  replication slot "pgcopydb" already exists
ERROR  pgsql.c:2482              SOURCE Context: CREATE_REPLICATION_SLOT "pgcopydb" LOGICAL "wal2json"
ERROR  snapshot.c:404            Failed to create a logical replication slot and export a snapshot, see above for details
```

I didn't executed:

```
$ pgcopydb stream sentinel set endpos --current
$ pgcopydb stream cleanup
```
since I'm not sure is it required.

Is there a correct way to resume terminated logical replication (to not start it from the beginning)? On dev/test environments I can of course start from scratch, but I'm not sure it will be possible on prod.

If there is a correct way to resume terminated logical replication, please share it.

Thanks!

**Comment by shubhamdhama** [comment]
@lospejos as long as you have snapshot intact, you should be able to resume using ` pgcopydb follow --resume`. Pass `--dir <path to pgcopydb working directory` if used earlier for previous command. This command worked fine for me, can you make sure you are using latest upstream? What version of pgcopydb you are using in above example?

**Comment by dimitri** [comment]
Closing for triage reasons, please open again with more information if still needed. Make sure the work directory is available when resuming.
