### ISSUE TITLE
Database names with forward slashes supported?

### ISSUE THREAD

**Issue by andyatkinson** [dimitri/pgcopydb#375]
Hello. Does pgcopydb support databases names with slashes in it? Unfortunately that's the source DB I'm working with and renaming it isn't easy. What I noticed is that it's converting the forward slash in the DB name into "%2f". 

Current DB name format: `db/name` 
What happens: `db%2fname`

I used ping here:
https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb.html

```
docker run --rm -it ghcr.io/dimitri/pgcopydb:latest pgcopydb ping --source $PGCOPYDB_SOURCE_PGUR
I --target $PGCOPYDB_TARGET_PGURI
19:38:59 1 INFO   Running pgcopydb version 0.12.12.g30ba542 from "/usr/local/bin/pgcopydb"
19:38:59 7 WARN   Failed to connect to "postgres://anatki@localhost:5432/db%2fname", retrying until the server is ready
...
19:39:11 7 ERROR  Connection to database failed: could not connect to server: Connection refused
```

And I'm on a Mac so I'm using the Docker executable. I can run `psql $PGCOPYDB_SOURCE_PGURI` and `psql $PGCOPYDB_TARGET_PGURI` and connect to each source and target side via psql.

It does seem like the slash was a bad idea to be part of the name but it was a decision that pre-dated me. So I'm hoping pgcopydb supports DB names with slashes in them or there's a workaround so I can use it along with other pg CLI tools I use like psql and pgslice.

Also, I think only the connection string format is supported and not the individual connection segment parts since the URI options were only what was listed by help (and what I'd normally want to use) so that didn't seem like a workaround.

```
19:48:08 1 INFO   Running pgcopydb version 0.12.12.g30ba542 from "/usr/local/bin/pgcopydb"
pgcopydb ping: Copy the roles from the source instance to the target instance
usage: pgcopydb ping  --source ... --target ...

  --source              Postgres URI to the source database
  --target              Postgres URI to the target database
```

Thanks!

**Comment by lospejos** [comment]
The workaround could be putting some service between `pgcopydb` and your database (f.e. `PGBouncer` etc).
It should be the tool that is able to communicate with databases containing slashes in their names.

**Comment by dimitri** [comment]
I just tested locally and it just works for me:

``` 
$ pgcopydb list tables --source "dbname=foo/bar"
19:01:53 46790 INFO   Running pgcopydb version 0.12.14.gd764133.dirty from "/Applications/Postgres.app/Contents/Versions/12/bin/pgcopydb"
19:01:53 46790 INFO   Listing ordinary tables in source database
19:01:53 46790 INFO   Fetched information for 1 tables, with an estimated total of 0 tuples and 8192 B
     OID |          Schema Name |           Table Name |  Est. Row Count |    On-disk size
---------+----------------------+----------------------+-----------------+----------------
  655980 |               public |              foo/bar |               0 |      8192 bytes
```

And yes in `--debug` mode we can see that it's using the connection string `postgres:///foo%2fbar`; which is how Postgres expects it in that case. See percent-encoding at https://www.postgresql.org/docs/current/libpq-connect.html and https://datatracker.ietf.org/doc/html/rfc3986#section-2.1.

``` 
19:02:42 46826 SQL    pgsql.c:510               Connecting to [source] "postgres:///foo%2fbar"
```

**Comment by andyatkinson** [comment]
Thanks @dimitri. This helped me realize it wasn't the database name at all, and it was actually my local Postgresql server being unreachable from the docker container (on Mac OS) without some extra configuration.

From this article: https://www.tutorialspoint.com/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-machine

I learned about: `HOSTNAME=docker.for.mac.host.internal`

I am now able to use `docker.for.mac.host.internal` in place of `localhost` when making the postgresql connection string URI. In retrospect, this might be quite obvious for people that regularly work with Docker. Hopefully it helps someone else out.

My full command is below and works as expected.

```sh
docker run --rm -it dimitri/pgcopydb:v0.12 pgcopydb list tables --source "postgresql://anatki:@docker.for.mac.localhost:5432/foo/bar"
```

Thanks!
