### ISSUE TITLE
Docs: `include-only-table` singular works, plural didn't

### ISSUE THREAD

**Issue by andyatkinson** [dimitri/pgcopydb#381]
Hello. When I used `include-only-tables` (table "plural") which the docs shows in the header, but not in the ini file example, it tried to copy all 315 tables for this database. 

When I used the singular form `include-only-table` as the example file shows, but not the header, the command tried to copy the 1 table (can see below) which is what I expected.

```
cat pgcopydb.ini
[include-only-table]
public.mytable

> docker run --mount type=bind,source="$(pwd)"/pgcopydb.ini,target=/pgcopydb.ini \
                                                        --rm -it dimitri/pgcopydb:v0.12 pgcopydb clone --source $PGCOPYDB_SOURCE_PGURI --target $PGCOPYDB_TARGET_PGURI --filter /pgcopydb.ini

01:39:48 1 INFO   Running pgcopydb version 0.12 from "/usr/local/bin/pgcopydb"
01:39:48 1 INFO   [SOURCE] Copying database from XXX
01:39:48 1 INFO   [TARGET] Copying database into XXX
01:39:48 1 INFO   Exported snapshot "00000003-00061C90-1" from the source database
01:39:48 16 INFO   STEP 1: fetch source database tables, indexes, and sequences
01:39:48 16 INFO   Fetched information for 8 extensions
01:39:48 16 INFO   Fetched information for 1 tables, with an estimated total of 27 tuples and 48 kB
```

So I think the documentation could be updated to use the singular form, or an alias is needed for the plural form if that's the intention.

Thanks!

**Comment by dimitri** [comment]
Thanks for reporting the issue! I think it would be too confusing to support both the forms; in particular when people are going to put both sections in their filtering INI setup, so I went for a docs typo fix.
