### ISSUE TITLE
Doesn't get creds

### ISSUE THREAD

**Issue by kostya-michaels** [dimitri/pgcopydb#429]
I set 
`PGCOPYDB_TARGET_PGURI="postgres://user2:mypassword@mycluster:6432/mydbname"` and get the following error after pgcopydb clone:
`6317 ERROR  pg_restore: error: could not execute query: ERROR:  must be member of role "postgres"
6317 ERROR  Command was: ALTER SCHEMA public OWNER TO postgres;
6317 ERROR  Failed to run pg_restore: exit code 1
6317 ERROR  Failed to clone source database, see above for details
6315 ERROR  clone process 6317 has terminated [6]
`

Who must be member of role "postgres"?
Anyway, I don't have such a role :-/

Please, help, kind Sir

**Comment by kostya-michaels** [comment]
Unfortunately, the mentioned error is specific for my infrastructure. My Postgres is running in cloud and the role `postgres` is locked by provider. So, I can't use this tool because I can't add my user to postgres.

**Comment by dimitri** [comment]
Please consider reading the docs at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_clone.html#options with all the available options, and then maybe consider using `--no-owner` and other options that allow for non-superuser pg_restore activity.
