### ISSUE TITLE
--split-tables-larger-than is not using the ctid

### ISSUE THREAD

**Issue by BVishwamitra** [dimitri/pgcopydb#461]
00:33:07 7468 INFO   Table "rec"."rec_unit_2022_07_2" is 24 GB large, which is larger than --split-tables-larger-than 5120 MB, but does not have a unique column of type integer (int2/int4/int8).
00:33:07 7468 WARN   Skipping same-table concurrency for table "rec_engine"."rec_unit_2022_07_2"

I am getting above error when I try to use the pgcopy with split-tables-larger-than option, In the document it is mentioned that "When a table is missing such a primary key column of an integer data type, pgcopydb then automatically resorts to using CTID based comparisons." It seems it didn't happen. Can you please let me know how to deal with this if the table do not have such options.

**Comment by dimitri** [comment]
Hi @BVishwamitra ; which version of pgcopydb are you using? I suppose you're viewing the developer docs for a release that didn't happen yet. Either build from source or use a developer version docker container (see the docs at https://pgcopydb.readthedocs.io/en/latest/install.html#docker-images) ; or use the docs for the version of pgcopydb that you have.
