### ISSUE TITLE
how to ignore public schema?

### ISSUE THREAD

**Issue by naiz0** [dimitri/pgcopydb#466]
Hi,

we want to copy one schema, with only two tables to a schema in another database.
we using this command:
`pgcopydb clone --source "postgres://tsadmin@xx.xx.xx.xx/ts_prodz" --target "postgres://tsadmin@xyz.database.azure.com/dm" --filters /var/lib/pgsql/xxx/pgcopydb/validation.filter   --restart --no-role-passwords --no-owner --no-acl  --skip-extensions –debug`

the content of validation.filter is:
[include-only-table]
ts_val_prodz.validation_entry
ts_val_prodz.flyway_schema_history

We dont want to copy anything from the public schema.

When we run the script, it fails with this error:
`pg_restore: error: could not execute query: ERROR:  must be superuser to create procedural language "plpythonu"`

We are using "plpythonu" only in the public schema, not in the two tables we want to copy.

how we can ignore this, because creating a plpythonu procedure is not possible in the azure cloud.

thanks in advance,
nico

**Comment by dimitri** [comment]
Hi @naiz0 ; you could try using the `[include-only-schema]` facility in the filtering, as documented at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_config.html#include-only-schema. That said I am not sure if that will solve your problem. I thought `--skip-extensions` would be enough to skip creating the language `plpythonu`. Can you share the relevant logs?

**Comment by dimitri** [comment]
> i cannot find the include-only-schema in this list.

My bad, it's not been released yet. You would need to use a development version of pgcopydb, either by compiling from sources or using the snapshot docker image built at each commit on the main branch by the CI/CD system. See docs at https://pgcopydb.readthedocs.io/en/latest/install.html for details.

Meanwhile we already see `--exclude-schema public` in the pg_dump and pg_restore activity so we won't improve on that. I'm surprised to see `TOC entry 1681; 2612 507309 PROCEDURAL LANGUAGE plpythonu` that said. Is it possible that you managed to install the language without using an extension?

**Comment by dimitri** [comment]
What I meant is that nowadays to create the language, as you're highlighting, we would use CREATE EXTENSION. It used to be that you had to run CREATE LANGUAGE directly. I'm surprised to see that pg_restore wants to issue a CREATE LANGUAGE command as opposed to a CREATE EXTENSION command. Can you double-check that you have the extension installed on your source server?

Then it might be that we can enhance `--skip-extensions` somehow. 

If you could share the relevant lines of the pgcopydb `pre.list` file to be found in the workdir (defaults to /tmp)?

**Comment by dimitri** [comment]
Thanks for the investigation. The part of the pre.list that I was interested into matches your `pg_language` catalog query and the fact that the extension is not installed. 

``` 
1689; 2612 507309 PROCEDURAL LANGUAGE - plpythonu postgres
```

One way to attempt to fix the situation would be to CREATE EXTENSION plpythonu on the source server. This should re-package the PROCEDURAL LANGUAGE entry as belonging to the extension without changing much of anything else on the server. Then pgcopydb would have a chance of going through when using the `--skip-extensions` option.

**Comment by dimitri** [comment]
Ok so now it works for the “offline” parts, and the replication parts are still broken because we are missing the filtering support there. Is that a good summary?

**Comment by dimitri** [comment]
We need to get to implementing filtering support for logical decoding. It's on the TODO list. Do you want to contribute the feature?

**Comment by dimitri** [comment]
Closing this issue now for triaging purposes. The error with decoding/catalogs is a separate issue, and the filtering support for logical decoding is on the todo list and I have made its own issue for this: https://github.com/dimitri/pgcopydb/issues/510.
