### ISSUE TITLE
Can pgcopydb use gzip for transfer?

### ISSUE THREAD

**Issue by sergeim-sravni** [dimitri/pgcopydb#468]
Hi,
for big databases network is more expensive that CPU. Can we compress data before sending?
By compressors like `gzip` or `zstd`.

**Comment by dimitri** [comment]
Hi @sergeim-sravni ; it could be possible to use the form `COPY ... TO PROGRAM 'compress ...'` and then on the receiving end `COPY ... FROM PROGRAM 'uncompress'` but then I'm not sure if/how to avoid spilling the contents to disk before being able to run the PROGRAM parts of the COPY.

That said, before investigating in how to solve that problem, can we check how much of a problem we have here. Do you have any numbers/telemetry from running pgcopydb with a big database that shows that the network is indeed your bottleneck?

**Comment by sergeim-sravni** [comment]
Actually, I cat explain our pattern. We frequently copy prod database to dev. Prod have big and complex firewall to dev. Copy 1Tb db from even free replica to dev too slow. I can make experiment for real numbers later.

**Comment by dimitri** [comment]
Closing for triage, please fee free to open again the issue with more information.
