### ISSUE TITLE
Users with @ in the database

### ISSUE THREAD

**Issue by 5lucasrocha** [dimitri/pgcopydb#473]
I'm triyng connect to clone db, but the users for connect to database are by default user@company-env-postgresql. When i try connect, the full address is user@company-env-postgresql@company-env-postgresql.postgres.database.azure.com and it try connect with "company-env-postgresql@company-env-postgresql.postgres.database.azure.com".
How to solve it?
Kr, Lucas Rocha

**Comment by dimitri** [comment]
See Postgres docs at https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING ; use the connection string format you prefer. You can use `pgcopydb --source "dbname=foo user=user@domain host=hostname"` if you want, or use percent-encoding in the URL form and write `user%40domain` instead.
