### ISSUE TITLE
Feature request: copy subset of data

### ISSUE THREAD

**Issue by jschaf** [dimitri/pgcopydb#481]
I have a multi-tenant database that I'd like to clone a small portion of for development. Each table includes a `tenant_id` column.  I'd like to copy data for a small subset of tenants instead of all tenants. This is a crude form of database subsetting, but is much simpler than sorting foreign keys topologically.

As a straw-man proposal, the syntax might be:

```sh
pgcopydb copy table-data \
  --table-filter='invoice: tenant_id IN (123, 456)' \
  --table-filter='bill: tenant_id IN (123, 456)'
```

As for the implementation, you'd probably need to convert the COPY statements to use a query instead of the table and columns to provide a WHERE clause.

### Alternatives

I've been looking for a few months. Here's all the database subsetting tools I know of. Jailer looks like the most promising.

- Post-process the dump and delete data: works but you still have to download the entire data set.

- [Condenser](https://github.com/TonicAI/condenser): sorts foreign keys topologically to implement a percentage subset. Uses pg_dump for schema and custom queries for data. The open-source tool claims it doesn't work well past a database size of 10 GB and they recommend their hosted offering. Parses results in Python, so not likely fast.

- [Replibyte](https://github.com/Qovery/replibyte): Rust tool that does a [full SQL dump](https://www.replibyte.com/docs/how-replibyte-works#:~:text=makes%20a%20full%20SQL%20dump%20of%20it) and subsets the dump.

- [Jailer](https://wisser.github.io/Jailer/): Java tool that looks like it can do everything. Seems primarily GUI based which might not scale well for hundreds of tables.

**Comment by dimitri** [comment]
See also https://github.com/dimitri/pgcopydb/issues/161.

I think a good idea to approach your problem here would be using Row-Level Security features of Postgres. You create a role that is specific to the migration, and attach your tenant_id restrictions to RLS rules for that role. Then connect to your source database with that role in the context of running pgcopydb.

Should then all be transparent.

**Comment by jschaf** [comment]
Oh my, using RLS is clever. I'll play around with it and re-open if I can't make it work.
