### ISSUE TITLE
pgcopydb compare command not computing the checksum as md5 hashed value 

### ISSUE THREAD

**Issue by Galileo1** [dimitri/pgcopydb#487]
I have been running the new pgcopydb compare against --source and --target and the aggregate computed hashtext that produces the checksum to compare between the two doesn't turn out to be correct even though row count is same. 

The debug logs for compare command shows the below query seems to be missing the results being hashed into md5 value? 

`Select count(1) as cnt,        sum(hashtext((__COLS__::text)::bigint) as chksum   from only __TABLE__`

Upon checking the documentation and running the below query. It produces the md5 hash which turned out to be same for both the tables. 

```
select count(1) as cnt,
       md5(
         format(
           '%%s-%%s',
           sum(hashtext(__COLS__::text)::bigint),
           count(1)
         )
       )::uuid as chksum
from only __TABLE__
```
Is this a bug? Or is expected outcome?

**Comment by dimitri** [comment]
Which version of pgcopydb are you using? The current main branch has the following code in https://github.com/dimitri/pgcopydb/blob/cd83ed69c3ebb5c4111346a4f28652d2c96851e2/src/bin/pgcopydb/schema.c#L3282-L3300

``` c
	/*
	 * Compute the hashtext of every single row in the table, and aggregate the
	 * results as a sum of bigint numbers. Because the sum of bigint could
	 * overflow to numeric, the aggregated sum is then hashed into an MD5
	 * value: bigint is 64 bits, MD5 is 128 bits.
	 *
	 * Also, to lower the chances of a collision, include the row count in the
	 * computation of the MD5 by appending it to the input string of the MD5
	 * function.
	 */
	appendPQExpBuffer(sql,
					  "select count(1) as cnt, "
					  "md5(format('%%s-%%s', "
					  "      sum(hashtext(%s::text)::bigint),"
					  "      count(1))"
					  ")::uuid as chksum "
					  "from only %s",
					  attrList->data,
					  table->qname);
```

**Comment by Galileo1** [comment]
I pulled down this tag from docker.io v0.13

**Comment by dimitri** [comment]
Please share logs as TEXT, otherwise we can't adjust font size, colors, we can't copy paste, we can't search.

Then, please share `pgcopydb version`. I used to be (in development) that we used bigint values for checksums, but that's not the case anymore. See https://github.com/dimitri/pgcopydb/pull/407.

**Comment by Galileo1** [comment]
I think the main difference was pull the latest release version from docker.io vs ghrc. The workflow doesn't show that you publish to docker.io anymore. After pulling from ghrc I can see the changes related to md5.
