### ISSUE TITLE
Copy Data Seems to Skip Creating Sequences

### ISSUE THREAD

**Issue by nps1984** [dimitri/pgcopydb#529]
I'm trying to migrate an azure postgresql database from 11 to 15. And because it is azure and because we have some automation built around SQL deployments, I'm playing with the various options of pgcopydb.

Below is the command I am running with a snippet of the output. Note that what I have in the filter file is:
```
[exclude-schema]
public
```

```
/usr/pgsql-15/bin/pgcopydb copy data --table-jobs 1 --index-jobs 1 --drop-if-exists --filters /home/myuser/skip_schema.ini    
11:06:13 3975567 INFO   Running pgcopydb version 0.13 from "/usr/pgsql-15/bin/pgcopydb"  
11:06:13 3975567 INFO   [SOURCE] Copying database from "postgres://adminuser%40postgresql-dev.postgres.database.azure.com@postgresql-dev.postgres.database.azure.com:5432/dbname"  
11:06:13 3975567 INFO   [TARGET] Copying database into "postgres://adminuser@v2-postgresql-dev.postgres.database.azure.com:5432/dbname"  
11:06:13 3975567 INFO   Exported snapshot "00000007-0002A628-1" from the source database
11:06:13 3975567 INFO   Copy data from source to target in sub-processes  
11:06:13 3975567 INFO   Create indexes and constraints in parallel  
11:06:13 3975567 INFO   Vacuum analyze each table  
11:06:13 3975567 INFO   Fetched information for 3 extensions  
11:06:14 3975567 INFO   Fetched information for 2449 tables, with an estimated total of 96 30 tuples and 95 kB  
11:06:15 3975567 INFO   Fetched information for 6499 indexes  
11:06:16 3975567 INFO   Fetching information for 2448 sequences  
11:07:47 3975567 INFO   STEP 6: starting 1 CREATE INDEX processes  
11:07:47 3975567 INFO   STEP 7: constraints are built by the CREATE INDEX processes  
11:07:47 3975567 INFO   STEP 8: starting 1 VACUUM processes  
11:07:47 3975567 INFO   STEP 5: copy Large Objects (BLOBs) in 1 sub-process  
11:07:47 3975567 INFO   STEP 9: reset sequences values  
11:07:47 3975809 INFO   Reset sequences values on the target database  
11:07:47 3975805 INFO   STEP 4: starting 1 table data COPY processes  
11:07:47 3975809 ERROR  [TARGET 24467] ERROR:  relation "schema.sequence_name" does not exist  
11:07:47 3975809 ERROR  [TARGET 24467] SQL query: select pg_catalog.setval(format('%I.%I', $1, $2), $3, $4)  
11:07:47 3975809 ERROR  [TARGET 24467] SQL params: 'schema', 'sequence_name', '1', 'false'  
11:07:47 3975809 ERROR  Failed to set sequence "schema"."sequence_name" last value to 1  
11:07:47 3975809 ERROR  Failed to set sequence values for "schema"."sequence_name"  
11:07:48 3975809 ERROR  [TARGET 24467] ERROR:  relation "schema.sequence_name" does not exist  
```

When I run the command I get a ton of errors saying similar to what is above. That none of my sequences exists and so it can't set the sequence to the appropriate value.

Since I am using the "copy data" option, I ensure the database exists with all of the schemas. Additionally all of the users and roles are deployed before executing the "copy data". But there is nothing under each schema, as I would expect this option to create all the objects and copy the data.

Am I missing something?

Thanks!

**Comment by dimitri** [comment]
As you can see in the docs at https://pgcopydb.readthedocs.io/en/latest/ref/pgcopydb_copy.html#pgcopydb-copy-data the `pgcopydb copy data` command copies the data section from source to target. This does not include SQL objects, only their associated data (table data using COPY, Large Object data, and sequence data using `setval`).

If you choose to use selective sub-commands of pgcopydb then you have to provide the right environment on the target database. In your case, you need to take care of everything about the schema. Otherwise, just use `pgcopydb clone` command maybe?

**Comment by nps1984** [comment]
Thanks for the clarification!
