### ISSUE TITLE
ERROR:  duplicate key value violates unique constraint "<table_name>_pkey"

### ISSUE THREAD

**Issue by lospejos** [dimitri/pgcopydb#557]
We're trying to migrate data on our `Production` database instance. This means, among other, frequent and massive data updates on relatively large database instance (up to 3 TB of data).

We used `pgcopydb` version `0.14.16`.

Initial load was ok. During online logical replication, an error occurred:

```
02:17:55 7477 INFO   File "/root/.local/share/pgcopydb/00000001000025E700000015.sql" does not exists yet, exit
02:17:56 7475 ERROR  Postgres query was interrupted: update pgcopydb.sentinel set startpos = $2, write_lsn = $1, flush_lsn = $2 returning startpos, endpos, apply, write_lsn, flush_lsn, replay_lsn
02:17:56 7475 ERROR  Failed to fetch pgcopydb.sentinel current values
02:17:56 7475 INFO   Reported write_lsn 25E7/15235EC0, flush_lsn 25E7/15235EC0, replay_lsn 25E7/13D709E8
02:17:56 7475 INFO   Streamed up to write_lsn 25E7/15235EC0, flush_lsn 25E7/15235EC0, stopping: endpos is 0/0
02:17:56 7475 INFO   Prefetch process has terminated
02:17:56 7474 INFO   Subprocesses for prefetch, transform, and catchup have now all exited
02:17:57 7474 INFO   Current sentinel replay_lsn is 25E7/14FE1E60
02:17:57 7474 INFO   Catching-up from existing on-disk files
02:17:57 13059 INFO   Transformed 211 JSON messages into SQL file "/root/.local/share/pgcopydb/00000001000025E700000015.sql"
02:17:58 13060 INFO   Catchup-up with changes from LSN 25E7/14FE1E60
02:17:58 13060 INFO   Replaying changes from file "/root/.local/share/pgcopydb/00000001000025E700000014.sql"
02:17:58 13060 ERROR  [TARGET 22205] ERROR:  duplicate key value violates unique constraint "<tablename>_pkey"
02:17:58 13060 ERROR  [TARGET 22205] DETAIL:  Key (id)=(247420390) already exists.
02:17:58 13060 ERROR  Failed to apply SQL from file "/root/.local/share/pgcopydb/00000001000025E700000014.sql", see above for details
02:17:58 7474 ERROR  Subprocess catchup with pid 13060 has exited with error code 12
02:17:58 7474 ERROR  Failed to catchup with on-disk files, see above for details
02:17:58 7471 ERROR  follow process 7474 has terminated [12]
```
After searching primary key `247420390` in the file `/root/.local/share/pgcopydb/00000001000025E700000014.sql`, we noticed, that insert statement didn't contain something eye-catching or non-usual. If you point me what to search, I can make additional data check.

I know that closed issue with almost the same title already exists #319 but I'm not sure that this is an issue duplicate. Rather it seems that previous issue was not completely fixed. Or these issues have different root cause, although they look very similar.

**Comment by VaibhaveS** [comment]
Do you have a test case to reproduce this?

**Comment by lospejos** [comment]
Sorry, we are finished our database migrations, and this issue was not repeated. So I have no test cases to reproduce this case. Probably we can postpone or dismiss this issue.

**Comment by dimitri** [comment]
Closing for triage then. Thanks for getting back to us, please consider opening the issue again with more relevant information if more work is needed.
