### ISSUE TITLE
Issue copying database from PostgreSQL 9.3 to 14.9 using pgcopydb

### ISSUE THREAD

**Issue by rahulkatkade7** [dimitri/pgcopydb#574]
I attempted to use pgcopydb to copy a database from PostgreSQL 9.3 to PostgreSQL 14.9 but encountered the following error:

SELECT e.oid, e.extname, n.nspname AS extnamespace,
zabbix-#        e.extrelocatable,
zabbix-#        array_length(e.extconfig, 1) AS count,
zabbix-#        generate_series(1, array_upper(e.extconfig, 1)) AS n,
zabbix-#        e.extconfig AS extconfig,
zabbix-#        format('%I', n.nspname) AS nspname,
zabbix-#        format('%I', c.relname) AS relname,
zabbix-#        e.extcondition[array_upper(e.extconfig, 1)]
zabbix-# FROM pg_extension e
zabbix-# LEFT JOIN pg_namespace n ON e.extnamespace = n.oid
zabbix-# LEFT JOIN LATERAL unnest(e.extconfig) WITH ORDINALITY AS t(extconfig, ord) ON true
zabbix-# LEFT JOIN pg_class c ON c.oid = t.extconfig
zabbix-# LEFT JOIN pg_namespace n ON c.relnamespace = n.oid
zabbix-# WHERE e.extconfig IS NOT NULL
zabbix-# ORDER BY oid, n;
ERROR:  syntax error at or near "WITH ORDINALITY"
LINE 20: LEFT JOIN LATERAL unnest(e.extconfig) WITH ORDINALITY AS t(e...

NOTICE [SOURCE] select e.oid, extname, extnamespace::regnamespace, extrelocatable,        0 as count, null as n,        null as extconfig, null as nspname, null as relname,        null as extcondition   from pg_extension e  where extconfig is null  UNION ALL   select e.oid, extname, extnamespace::regnamespace, extrelocatable,          array_length(e.extconfig, 1) as count,          extconfig.n,          extconfig.extconfig, n.nspname, c.relname,          extcondition[extconfig.n]     from pg_extension e,          unnest(extconfig) with ordinality as extconfig(extconfig, n)           left join pg_class c on c.oid = extconfig.extconfig           join pg_namespace n on c.relnamespace = n.oid    where extconfig.extconfig is not null order by oid, n;
03:35:18 2408242 ERROR  [SOURCE] ERROR:  syntax error at or near "with ordinality"
03:35:18 2408242 ERROR  [SOURCE] LINE 1: ...  from pg_extension e,          unnest(extconfig) with ordin...
03:35:18 2408242 ERROR  [SOURCE]                                                              ^
03:35:18 2408242 ERROR  SQL query: select e.oid, extname, extnamespace::regnamespace, extrelocatable,        0 as count, null as n,        null as extconfig, null as nspname, null as relname,        null as extcondition   from pg_extension e  where extconfig is null  UNION ALL   select e.oid, extname, extnamespace::regnamespace, extrelocatable,          array_length(e.extconfig, 1) as count,          extconfig.n,          extconfig.extconfig, n.nspname, c.relname,          extcondition[extconfig.n]     from pg_extension e,          unnest(extconfig) with ordinality as extconfig(extconfig, n)           left join pg_class c on c.oid = extconfig.extconfig           join pg_namespace n on c.relnamespace = n.oid    where extconfig.extconfig is not null order by oid, n
03:35:18 2408242 ERROR  SQL params:
03:35:18 2408242 ERROR  Failed to list extensions
03:35:18 2408242 NOTICE [SOURCE] COMMIT;

**Comment by hanefi** [comment]
`WITH ORDINALITY` clause was first introduced in PG 9.4 and pgcopydb uses several queries that look-up source schema involving this clause. Would you like to contribute by rewriting those queries with the same functionality, but without using those clauses?

There are 4 queries in file https://github.com/dimitri/pgcopydb/blob/main/src/bin/pgcopydb/schema.c that should be rewritten to support PG 9.3.

I could think of rewriting those clauses in ordinary subqueries in lateral joins. However lateral joins were introduced in 9.3 and if we decide to rewrite the queries that way we can only add support for 9.3.
