### ISSUE TITLE
Sequence numbers values are incorrect after restore

### ISSUE THREAD

**Issue by BlowaXD** [dimitri/pgcopydb#6]
Hi,

I've been using your tool, thanks for that, pretty convenient, however, it seems like the Sequence values are not correct after the restore.

Before restore:
![image](https://user-images.githubusercontent.com/16936368/149965706-9207ebb7-9962-41c8-accf-783d44b242a9.png)
After restore:
![image](https://user-images.githubusercontent.com/16936368/149965761-14c42640-7265-46ad-9e73-c88e1ca4b2b2.png)

Is there any flag I should have missed ?

```sh
pgcopydb copy-db --source="postgres://user:pass@ip:port/sourcedb" --target="postgres://user:pass@ip:port/targetdb"
```

Using raw `pg_dump` + `pg_restore` without any flag works tho

Thanks!

**Comment by dimitri** [comment]
Hi @BlowaXD ; thanks for using pgcopydb version 0.2 and opening this issue! 

I now realise that the `--section=data` part of pg_dump and pg_restore actually includes the table-data, then the sequence “data” (set), and also the large objects (blobs). Per https://github.com/postgres/postgres/blob/master/src/bin/pg_dump/pg_dump_sort.c#L79-L83 we see:

```c
	PRIO_PRE_DATA_BOUNDARY,		/* boundary! */
	PRIO_TABLE_DATA,
	PRIO_SEQUENCE_SET,
	PRIO_BLOB_DATA,
	PRIO_POST_DATA_BOUNDARY,	/* boundary! */
```

I will see about how to implement the sequence set operations to solve this issue, and I suppose I will have to see about those table blobs too. Is it possible to ask pg_dump for an archive file that contains the archive TOC entries for the --section=data but does not contain the table data itself?

**Comment by BlowaXD** [comment]
Hi,

Thanks for your fast response, I can't answer your question as I've recently been in the need of doing that db transfer, didn't have time to study much about `pg_dump` capabilities.

If you need further testing, I could check later this weekend but the two following days I'm too busy for that

**Comment by dimitri** [comment]
I just pushed a commit that implements support for sequences. You can either restart the whole process with the main `pgcopydb copy-db` command as you did already, or you can consider `pgcopydb copy sequences` to take care of the sequences themselves without restarting the whole process.

Either way you need to now compile pgcopydb from source and try again. Please report your findings!

**Comment by dimitri** [comment]
See https://github.com/dimitri/pgcopydb/commit/600b9665175cb1ad4517b025961f801273afe008 for the commit.
