### ISSUE TITLE
Error in image created from main branch

### ISSUE THREAD

**Issue by pratikshetty1994** [dimitri/pgcopydb#606]
I get the following error when using the main branch.

06:54:04.998 8 INFO   Found 0 indexes (supporting 0 constraints) in the target database
corrupted size vs. prev_size

**Comment by dimitri** [comment]
Closing for lack of information. If you imagine we can do anything about this issue with the lack of shared context, well, sorry but not possible. Please consider opening again with enough information for us to be able to understand what you're talking about, or consider contributing a bugfix by opening a Pull Request.
