### ISSUE TITLE
Syntax error in pg_restore from improperly generated copy SQL

### ISSUE THREAD

**Issue by alexkuretz** [dimitri/pgcopydb#634]
Using the docker image `dimitri/pgcopydb:v0.15` copying a database between two RDS instances. 

The command I'm running: `pgcopydb clone --table-jobs 16 --index-jobs 16 --no-role-passwords --no-owner --no-acl --fail-fast --skip-extensions`

The generated SQL has an extra comma, there should be one more column "cid" after reference_type. The table is created properly on the target DB, I don't know why the copy sql is generated improperly.

EDIT: I'm now trying it with the previous v0.14 docker image and am not encountering the error, will see if it completes my clone.

Let me know if you need any further information!

Log snippet:
```
00:46:36.064 6520 INFO   Skipping large objects: none found.
00:46:36.071 6520 INFO   STEP 9: reset sequences values
00:46:36.076 6593 INFO   Reset sequences values on the target database
00:46:36.158 6558 ERROR  [SOURCE 17992] [42601] ERROR:  syntax error at or near "FROM"
00:46:36.158 6558 ERROR  [SOURCE 17992] LINE 1: ...esource, tid, uid, reference_rn, reference_type,  FROM ONLY ...
00:46:36.158 6558 ERROR  [SOURCE 17992]                                                              ^
00:46:36.158 6558 ERROR  [SOURCE 17992] Context: copy (SELECT id, rn, type, action, ts, resource, tid, uid, reference_rn, reference_type,  FROM ONLY schema.event_item) to stdout
00:46:36.158 6558 ERROR  Failed to copy data for table with oid 71244919 and part number 0, see above for details
00:46:36.161 6541 ERROR  Sub-process 6558 exited with code 12
00:46:36.161 6541 ERROR  Signaling other processes to terminate (see --fail-fast)
00:46:36.161 6541 FATAL  Terminating all processes in our process group
``` 

Schema:
```
                                            Table "schema.event_item"
     Column     |           Type           | Collation | Nullable |                    Default                     
----------------+--------------------------+-----------+----------+------------------------------------------------
 id             | integer                  |           | not null | nextval('schema.event_item_id_seq'::regclass)
 rn             | text                     |           |          | 
 type           | text                     |           |          | 
 action         | text                     |           |          | 
 ts             | timestamp with time zone |           |          | 
 resource       | text                     |           |          | 
 tid            | text                     |           |          | 
 uid            | text                     |           |          | 
 reference_rn   | text                     |           |          | 
 reference_type | text                     |           |          | 
 cid            | text                     |           |          | 
```

**Comment by dimitri** [comment]
Hi @alexkuretz ; thanks for reporting the issue. I'm not seeing where it happens in the source code at the moment, could you maybe run again with `--debug` or even `--trace` log level, and then send more details here?

**Comment by alexkuretz** [comment]
Yeah I had run it with --verbose and that didn't tell me anything extra. I did a code search and didn't see anything obvious other than the function name itself but not where it's called from. I ran it with --debug just now and got a little more info, hopefully it's helpful. I also tried with --trace but do not believe it included anything additionally useful.

```
20:32:29.922 7381 NOTICE table-data.c:1259         COPY schema.event_item
20:32:29.922 7381 SQL    pgsql.c:1501              [TARGET 28869] BEGIN;
20:32:29.923 7381 SQL    pgsql.c:2314              TRUNCATE ONLY schema.event_item
20:32:29.923 7381 SQL    pgsql.c:1501              [TARGET 28869] TRUNCATE ONLY schema.event_item;
20:32:29.931 7381 SQL    pgsql.c:2765              copy (SELECT id, rn, type, action, ts, resource, tid, uid, reference_rn, reference_type,  FROM ONLY schema.event_item) to stdout;
20:32:29.931 7381 ERROR  pgsql.c:2811              [SOURCE 23890] [42601] ERROR:  syntax error at or near "FROM"
20:32:29.931 7381 ERROR  pgsql.c:2819              [SOURCE 23890] LINE 1: ...esource, tid, uid, reference_rn, reference_type,  FROM ONLY ...
20:32:29.931 7381 ERROR  pgsql.c:2819              [SOURCE 23890]                                                              ^
20:32:29.931 7381 ERROR  pgsql.c:2826              [SOURCE 23890] Context: copy (SELECT id, rn, type, action, ts, resource, tid, uid, reference_rn, reference_type,  FROM ONLY schema.event_item) to stdout
20:32:29.931 7381 SQL    pgsql.c:404               Disconnecting from [source] "postgres://redacted?keepalives=1&keepalives_idle=10&keepalives_interval=10&keepalives_count=60"
20:32:29.931 7381 ERROR  table-data.c:777          Failed to copy data for table with oid 71244919 and part number 0, see above for details
20:32:29.931 7381 SQL    pgsql.c:404               Disconnecting from [target] "postgres://redacted?keepalives=1&keepalives_idle=10&keepalives_interval=10&keepalives_count=60"
```

**Comment by dimitri** [comment]
The logs share show the problem clearly, but it's the same as previously. What I'm missing is how we build the incomplete SELECT statement with a partial column list. Could you share a SQL script that installs a schema where the problem always happen to you, so that we could add that SQL script to our unit test suite and fix it?

**Comment by VaibhaveS** [comment]
@alexkuretz, can you please share a reproducible test case?

**Comment by alexkuretz** [comment]
Version 0.14 worked for me so I've been busy with that migration and plan to keep using that since I've encountered several issues with 0.15. I provided the schema that was failing for me. I will try to get a test database set up to see if it fails in the same way and if it does I'll provide the SQL to create that setup.

**Comment by VaibhaveS** [comment]
Thanks @alexkuretz for the schema, I tried a migration with `V0.15` and it's working fine.
 
> 14:11:21.123 1137675 SQL    pgsql.c:2795              copy (SELECT id, rn, type, action, ts, resource, tid, uid, reference_rn, reference_type, cid FROM ONLY schema.event_item) to stdout;

**Comment by dimitri** [comment]
Thanks for testing with the provided schema @VaibhaveS ; closing the issue for triage. Consider opening again if you have more information or if the issue still needs fixing.
