### ISSUE TITLE
free(): corrupted unsorted chunks on AWS Ubuntu 22.04.2 LTS

### ISSUE THREAD

**Issue by bogvak** [dimitri/pgcopydb#656]
During executing of command `pgcopydb compare schema` it's bring error
```
free(): corrupted unsorted chunks
```
a bit of debug context
```
23:12:30.422 4477 INFO   sequences.c:64            Fetching information for 1 sequences
23:12:30.422 4477 SQL    pgsql.c:1501              [SOURCE 39254] select has_sequence_privilege($1, $2);;
23:12:30.422 4477 SQL    pgsql.c:1514              [SOURCE 39254] 'public.django_migrations_id_seq', 'select'
23:12:30.443 4477 SQL    pgsql.c:1501              [SOURCE 39254] select last_value, is_called from public.django_migrations_id_seq;
23:12:30.483 4477 SQL    pgsql.c:1501              [SOURCE 39254] COMMIT;
23:12:30.506 4477 SQL    pgsql.c:404               Disconnecting from [source] "xxx"
23:12:30.507 4477 NOTICE copydb_schema.c:1200      Skipping target catalog preparation
23:12:30.513 4477 INFO   compare.c:588             [SOURCE] table: 5, index: 20, constraint: 9, sequence: 1
23:12:30.513 4477 INFO   compare.c:594             [TARGET] table: 5, index: 20, constraint: 9, sequence: 1
free(): corrupted unsorted chunks
4477 Aborted                 (core dumped) pgcopydb compare schema --debug
```
```
23:20:22.711 4624 INFO   Running pgcopydb version 0.15-1.pgdg22.04+1 from "/usr/bin/pgcopydb"
pgcopydb version 0.15-1.pgdg22.04+1
compiled with PostgreSQL 16.1 (Ubuntu 16.1-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
compatible with Postgres 11, 12, 13, 14, 15, and 16
```

Previuos version - 13 worked fine on the same machine.
I tried to install version 14 - but seems there not such version in APT repository.
I would really appreciate if you may advise how I may install some previuos version that doesn't have this bug.
Thanks in advance!

**Comment by dimitri** [comment]
I think the recent PR https://github.com/dimitri/pgcopydb/pull/647 should fix it. Can you build from sources and try again?

**Comment by jlewis-spotnana** [comment]
I also ran into this issue, and can confirm that building from `main` fixes it. (I tested with commit `32fb16e` specifically.)

---

For others looking to test on Ubuntu 22.04, you first need to install a myriad of libraries. The list in [Dockerfile.debian](https://github.com/dimitri/pgcopydb/blob/main/Dockerfile.debian) worked for me. You can then run `make` from the root (after cloning this repo) and you should be gtg.

**Comment by dimitri** [comment]
See https://github.com/dimitri/pgcopydb/pull/670 for improving build-from-source docs.
