### ISSUE TITLE
EPAS/EDB compatibility

### ISSUE THREAD

**Issue by andres-chavez-bi** [dimitri/pgcopydb#674]
Hi, I'm not sure this is actually an issue, but we're currently testing the tool on an enterprise environment, using epas/edb's version of postgres (version 12 and 14) and I'm seing warnings and errors which are not seen on the community version of the engine. I've attached the output to the issue. 
I have not found any mention on the documentation related to this compatibility and thus I wanted to open the question.

Here're my environment from where I execute the tool:

Linux WKS0001900845 5.15.133.1-microsoft-standard-WSL2 #1  x86_64 GNU/Linux
[epas_error_log.txt](https://github.com/dimitri/pgcopydb/files/14208191/epas_error_log.txt)

Here's my command:
`pgcopydb clone --source $PGCOPYDB_SOURCE_PGURI --target $PGCOPYDB_TARGET_PGURI --verbose --skip-vacuum --index-jobs 2 --restore-jobs 2 --restart --drop-if-exists`

Basically the issue seems to be a permission denied on some sys schema objects - we're using enterprisedb as a superuser:

```
11:18:09.057 453 ERROR  [TARGET 9454] ERROR:  permission denied: "callback_queue_table" is a system catalog
11:18:09.057 453 ERROR  [TARGET 9454] ERROR:  permission denied: "callback_queue_table" is a system catalog
11:18:09.057 453 ERROR  [TARGET 9454] SQL query: DROP TABLE IF EXISTS  public.pgbench_accounts, public.pgbench_tellers, sys.product_component_version, sys.dual, public.pgbench_branches, pgagent.pga_jobagent, pgagent.pga_jobclass, pgagent.pga_job, pgagent.pga_jobstep, sys.callback_queue_table, sys.edb_dbms_redact_full_default_values, sys.plsql_profiler_rawdata, sys.plsql_profiler_runs, sys.plsql_profiler_units, sys."edb$snap", sys."edb$system_waits", sys."edb$session_waits", sys."edb$session_wait_history", pgagent.pga_schedule, pgagent.pga_joblog, pgagent.pga_jobsteplog, sys."edb$stat_all_indexes", sys."edb$stat_all_tables", sys."edb$stat_database", sys."edb$statio_all_indexes", sys."edb$statio_all_tables", pgagent.pga_exception, public.test, public.pgbench_history CASCADE
```

Thank you!

**Comment by dimitri** [comment]
Well pgcopydb does not have support for (what I believe is) a proprietary fork of Postgres. Please consider contributing this support, or asking your proprietary vendor to contribute support for their product to pgcopydb. Closing for triage, even though I will accept a PR that implements the support, and will also accept to spend time reviewing such PR until it's ready for merge and all.
