### ISSUE TITLE
forwards compatibility for pg_dump?

### ISSUE THREAD

**Issue by brettgoulder** [dimitri/pgcopydb#678]
Hi Dimitri,

I had a quick question about the docs. In it, you state "The tools version should match the Postgres version of the target database.". Is that strictly true, or is there forwards compatibility? [pg_dump](https://www.postgresql.org/docs/current/app-pgdump.html#notes) docs state:

"Because pg_dump is used to transfer data to newer versions of PostgreSQL, the output of pg_dump can be expected to load into PostgreSQL server versions newer than pg_dump's version."

Thanks!

**Comment by dimitri** [comment]
I will provide here the Postgres community favourite answer: what happens when you try?

The standard operation procedure is to use the pg_dump and pg_restore versions that match with the TARGET system.
