### ISSUE TITLE
[SQLite 5] database is locked

### ISSUE THREAD

**Issue by FoxMoorhuhn** [dimitri/pgcopydb#695]
**pgcopydb version 0.15
compiled with PostgreSQL 11.21 (Debian 1:11.21-astra.se6+ci1) on x86_64-pc-linux-gnu, compiled by gcc (AstraLinuxSE 8.3.0-6) 8.3.0, 64-bit
compatible with Postgres 11, 12, 13, 14, 15, and 16**

**Command line**
_/usr/lib/postgresql/11/bin/pgcopydb clone --table-jobs=1 --index-jobs=1 --restore-jobs=1 --skip-vacuum --source="postgresql://postgres:123@localhost:5433/db1" --target="postgresql://postgres:123@localhost:5432/restdb" 2>pgcopydb_$(date +"%d_%m_%Y_%H_%M_%S").log_

Source DB on  Postgres Pro ent 15
Target DB on Postgres Pro ent 15

I tried changing the number of jobs (1-5), the result is the same

Process fails with an errors 
**First error** _Failed to execute statement: update timings set done_time_epoch_ 
[pgcopydb_05_03_2024_22_09_50.log](https://github.com/dimitri/pgcopydb/files/14500273/pgcopydb_05_03_2024_22_09_50.log)

**Comment by dimitri** [comment]
See also https://github.com/dimitri/pgcopydb/issues/677 ; it seems that the current code in the main branch does not have that problem. Closing this issue for triage, consider opening again with more information if more work is needed.
