### ISSUE TITLE
Clone fails on existing schema

### ISSUE THREAD

**Issue by sagar-git-hub** [dimitri/pgcopydb#718]
Hi Team,

I am creating my target DB in AWS Hyperscalar in cloud foundry. My source DB is also in CF provided by AWS Hyperscalar.
When creating target DB, it creates some default functions and schema 'public'. I tried to do a clone using command

**pgcopydb clone --no-owner --no-acl**

I get the error saying schema 'public' already exists. I then tried with command

**pgcopydb clone --no-owner --no-acl --drop-if-exists**

It sill fails saying the user does not have sufficient permission to drop the schema. But, as I said, the schema is created by default by hyperscalars during DB creation
. Can you please help. I have attached logs for reference
[phy_logical_log.txt](https://github.com/dimitri/pgcopydb/files/14721694/phy_logical_log.txt)

**Comment by dimitri** [comment]
Hi @sagar-git-hub ; which version of pgcopydb are you using? I think with current version of pgcopydb that can't happen anymore, but that might require compiling from sources or waiting until v0.16. Closing this issue for triage reasons, please provide more information for re-opening the issue if more work is needed here.
