### ISSUE TITLE
"pgcopydb copy db" ERROR:  invalid snapshot identifier

### ISSUE THREAD

**Issue by ShrikanthDeva** [dimitri/pgcopydb#720]
Hi Team, 

I wanted to copy `testing_1` database which has 20 tables from `Postgres 14` to `Postgres 16`.
But I'm getting  `ERROR  pg_dump: error: query failed: ERROR:  invalid snapshot identifier: "00000003-00000069-1"`

![image](https://github.com/dimitri/pgcopydb/assets/94846398/124bd634-5860-4651-9633-65d90c3a8e90)

I'm using `pgcopydb` Version: 14
I've attached the trace log file for your reference.
[pgcopydb_log.txt](https://github.com/dimitri/pgcopydb/files/14739168/pgcopydb_logs.txt)

**Comment by toxeus** [comment]
@ShrikanthDeva how did you fix this issue?

**Comment by ShrikanthDeva** [comment]
Hey @toxeus,

I hope this isn't too late! It seems `pgcopydb` might be stuck on a snapshot of a database, that is currently unavailable.

As a quick fix, try removing the `/tmp/pgcopydb/` directory (be cautious, this deletes all contents) and then re-running the copy db command.

Command: `rm -rf /tmp/pgcopydb/`

Since the metadata is gone pgcopydb won't resume the previous attempt, it will start a fresh copy.

Let me know if this worked for you as well :)

**Comment by dimitri** [comment]
You can use the `--restart` option to the same effects.

**Comment by toxeus** [comment]
@ShrikanthDeva thank you for sharing your solution. I did solve it by passing `--not-consistent` as @dimitri suggested [here](https://github.com/dimitri/pgcopydb/issues/582#issuecomment-1860088348). Now that I have learned about `--restart` I will use that in the future instead.
