### ISSUE TITLE
`pgcopydb 15` install error: 'sqlite3.h' file not found

### ISSUE THREAD

**Issue by ShrikanthDeva** [dimitri/pgcopydb#721]
I was trying to install release 15 from the source code. But I caught into `error: 'sqlite3.h' file not found` error.
![image](https://github.com/dimitri/pgcopydb/assets/94846398/7d6fba30-67ad-4649-82f4-00d968b74f30)

**Comment by dimitri** [comment]
Hi @ShrikanthDeva. First, please avoid sharing text as an image. I can't adjust the font size, the colors, I can't copy/paste, I can't search&find within the text. It's only problematic, I won't even try to read it.

Now, about the file not found error, this looks like a build-dependency problem. Please review our documentation section about building from sources at https://pgcopydb.readthedocs.io/en/latest/install.html#build-from-sources.

**Comment by ShrikanthDeva** [comment]
Hey @dimitri, Thanks for taking the time to look into this, I'll look at the installation document and the docker file. Also sorry for sharing the issue as an image.
PS: I don't know the best practices this was my first ever issue.
