### ISSUE TITLE
Skip ALTER DATABASE commands

### ISSUE THREAD

**Issue by groeneman** [dimitri/pgcopydb#730]
I'm experimenting with using pgcopydb to migrate from Heroku to AWS Aurora Postgres.

When I attempt to clone the DB I'm getting an error:

```
00:52:24.398 12833 INFO   ALTER DATABASE "my_database" SET "temp_tablespaces" TO 'ephemeral';
00:52:24.399 12833 ERROR  [TARGET 52359] ERROR:  permission denied to set parameter "temp_tablespaces"
```

Seemingly because this parameter can't be set in AWS Aurora. Is there anyway to skip the copying of database settings. Ideally I'd just copy the schema (tables, indexes, foreign keys, etc...) and not any of the database settings from my source database?

It seems like I can manually `pg_dump`/`pg_restore` the `pre-data` and `post-data` and then use `pgcopydb copy data` to copy just the data/indexes, but I'd love to use the tool end-to-end if possible.

Thanks for your work on this very helpful tool!

**Comment by dimitri** [comment]
See also #726.

I am wondering if there is a way to inquire about privileges to edit a setting before running the ALTER DATABASE SET command, or maybe we should use sub-transactions there and turn errors into warnings and continue processing. I'd like to have your opinion @VaibhaveS and @shubhamdhama if you're around?
