### ISSUE TITLE
Failed to lookup table oid 113619454 in internal catalogs, see above for details

### ISSUE THREAD

**Issue by kbarber** [dimitri/pgcopydb#755]
We get this type of error when sometimes running a clone with `pgcopydb clone --split-tables-larger-than XXX`:

```
2024-04-22 12:20:42.533 81 ERROR  table-data.c:865          Failed to lookup table oid 31678216 in internal catalogs, see above for details
2024-04-22 12:20:42.533 76 SQL    pgsql.c:1559              [TARGET 4046] SET client_encoding TO 'UTF-8';
2024-04-22 12:20:42.533 81 ERROR  table-data.c:790          Failed to copy data for table with oid 31678216 and part number 2, see above for details
```

While trying to track down a reproduction for another case (https://github.com/dimitri/pgcopydb/issues/700) I kept hitting this exact issue in a much smaller reproduction now, so I tried to make it even smaller and raise a separate ticket on it. I've seen it enough in my testing, maybe 1 in 1000 transfers perhaps but its real enough :-).

Anyway, if you do this:

```
create table foo (id int);
insert into foo values (1), (2), (3), (4), (5), (6), (7), (8), (9), (10);
```

And do a very small split:

```
pgcopydb clone
  --source x
  --target y
  --debug \
  --fail-fast \
  --split-tables-larger-than 1
```

You get the same error, and it looks like its miscounting partitions. The partition detection shows 2 partitions:

```
14:12:50.013 675 DEBUG  schema.c:3334             Partition public.foo#1: 0 - 0 (1)
14:12:50.013 675 DEBUG  schema.c:3334             Partition public.foo#2: 1 - 1 (1)
```

Then the error shows the workers reaching for partition 3 & 4 which do not exist:

```
14:13:31.625 691 ERROR  table-data.c:865          Failed to lookup table oid 41250 in internal catalogs, see above for details
14:13:31.625 691 ERROR  table-data.c:790          Failed to copy data for table with oid 41250 and part number 3, see above for details
14:13:31.645 688 ERROR  table-data.c:865          Failed to lookup table oid 41250 in internal catalogs, see above for details
14:13:31.645 688 ERROR  table-data.c:790          Failed to copy data for table with oid 41250 and part number 4, see above for details
```

I think the production cases I see relate to this miss-counting on a smaller level, but I can't be sure. I've seen this bug with split sizes of 50 MB and 900 partitions for real data, so I think the issues are related. I hope it helps either way.

Has anyone seen this before and can perhaps confirm my repro?

**Comment by VaibhaveS** [comment]
Yep can confirm the repro

**Comment by kbarber** [comment]
Thanks @dimitri
