### ISSUE TITLE
bug?: include-table filter fails due to oid collision with postgis extension

### ISSUE THREAD

**Issue by alefminus** [dimitri/pgcopydb#772]
Hi,

 I have no produced a simple reproduction for this yet, but using latest commit (4f41dd430c8160876b89c26a99d81fc068d54c99) and a include-table with a single exclude-schema filter I got the table excluded. Some added log messages and I saw that the exclusion was based on oid from ```copydb_objectid_is_filtered_out``` in branch ```if (result.oid != 0)```.
Looking at the sqlite filter contained that oid but the restore_list_name is "postgis" which is unrelated to the table.

Is this a known issue?

More details:
I'm running
```bash
./src/bin/pgcopydb/pgcopydb clone \
  --verbose \
  --no-role-passwords \
  --no-owner \
  --no-acl \
  --dir $DIR \
  --source $SOURCE \
  --target $TARGET \
  --skip-extensions \
  --filters $FILTERS \
   2>&1| tee clone.$(git describe).$(date +%Y%m%d_%H%M%S).log
```
DIR=test3

Where $FILTERS points to a file containing:
```
[include-only-table]
public.sensor_data_raw
[exclude-schema]
grafana
```

And the output shows that the sensor_data_raw table is filtered out:
```
2024-05-08 16:09:00.301 3968766 NOTICE copydb_schema.c:914       copydb_objectid_filtered_out based on oid 16417
2024-05-08 16:09:00.301 3968766 NOTICE dump_restore.c:718        Skipping filtered-out dumpId 662: TABLE 1259 16417 public sensor_data_raw postgres
```

The additional prints are due to this patch:
```patch
--- a/src/bin/pgcopydb/copydb_schema.c
+++ b/src/bin/pgcopydb/copydb_schema.c
@@ -911,6 +911,7 @@ copydb_objectid_is_filtered_out(CopyDataSpec *specs,

                if (result.oid != 0)
                {
+                       log_notice("copydb_objectid_filtered_out based on oid %d", result.oid);
                        return true;
                }
        }
@@ -925,6 +926,7 @@ copydb_objectid_is_filtered_out(CopyDataSpec *specs,

                if (!IS_EMPTY_STRING_BUFFER(result.restoreListName))
                {
+                       log_notice("copydb_objectid_filtered_out based on rlname");
                        return true;
                }
        }
```

But filters.db shows:
```bash
❯ sqlite3 test3/schema/filter.db 'select * from filter where oid = 16417'
16417|postgis|extension
```

Thanks,
Alon

**Comment by arajkumar** [comment]
I don't really know whether oid can have duplicate.

Could you please run the following query on your source database instance and share us the results?

```
select * from pg_class where oid = 16417;

select * from pg_extension where oid = 16417;

```

**Comment by scottjacobsen** [comment]
I'm hitting this one today. I'll see if I can come up with a minimal test case.
