### ISSUE TITLE
Error copying between two managed DBs

### ISSUE THREAD

**Issue by DanRStevens** [dimitri/pgcopydb#8]
I got the following error while trying to copy between two managed DBs on Digital Ocean:
> 00:20:38 992269 ERROR pg_restore: while PROCESSING TOC:
> 00:20:38 992269 ERROR pg_restore: from TOC entry 6267; 0 0 COMMENT EXTENSION tablefunc
> 00:20:38 992269 ERROR pg_restore: error: could not execute query: ERROR:  must be owner of extension tablefunc
> 00:20:38 992269 ERROR Command was: COMMENT ON EXTENSION tablefunc IS 'functions that manipulate whole tables, including crosstab';
> 00:20:39 992269 ERROR pg_restore: warning: errors ignored on restore: 1
> 00:20:39 992269 ERROR Failed to run pg_restore: exit code 1

The command was run as the `doadmin` user, which I believe has more restricted access when it comes to things like extensions.

The schema was copied over, but no data was copied.

I updated to the version released a few days ago, and tried the `--no-owner` flag (#5), though it had no effect on the error.

**Comment by dimitri** [comment]
I believe now using the new options `--no-comments --no-acl` should allow proceeding when the target role isn't superuser and in your Cloud Hosting case. Please test when you can (before next release, consider building locally) and if you need to consider re-opening this issue with more details!
