### ISSUE TITLE
ERROR Failed to open file "/tmp/pgcopydb/run/tables/80851245.done"

### ISSUE THREAD

**Issue by skel0** [dimitri/pgcopydb#855]
Hi all,

I am newbie with pgcopydb. I have to copy a bunch of DBs from one Linux server to Azure DB (separated DBs). I got an error cloning a database using pgcopydb. This is my scenario:

Source DB:
Running in a CentOS 7.9 VM with PostgreSQL v15.2.
I installed pgcopydb in the source host (CentOS 7.9) where the source DB is running: pgcopydb_15-0.10-1.rhel7.x86_64

Destination DB:
Microsoft Azure DB for PostgreSQL v16.3 (DBaaS)

Is above scenario supported for pgcopydb?

And used below command line to clone the DB:

export PGCOPYDB_SOURCE_PGURI="port=5432 host=A.B.C.D dbname=destdb user=sourceuser password=************"
export PGCOPYDB_TARGET_PGURI="port=5432 host=X.Y.Z.S dbname=destdb user=targetuser password=************"

pgcopydb copy-db --table-jobs 12 --index-jobs 12 --restart --no-acl --filters pgcopydb_filter.txt

After 45 mins aprox. finished with below error.

10:28:07 16522 INFO  Running pgcopydb version 0.10 from "/usr/pgsql-15/bin/pgcopydb"
...
...
11:13:25 16527 INFO  COPY phase is done, now waiting for vacuum, index, blob, and sequences processes
11:13:25 16527 INFO  STEP 10: restore the post-data section to the target database
11:13:25 16527 INFO   /bin/pg_restore --dbname 'postgres://targetuser@X.Y.Z.S:5432/destdb?' --single-transaction --no-acl --use-list /tmp/pgcopydb/schema/post.list /tmp/pgcopydb/schema/post.dump
11:13:27 16527 ERROR Failed to open file "/tmp/pgcopydb/run/tables/80851245.done": No such file or directory
11:13:27 16527 ERROR Failed to prepare the summary table

The file /tmp/pgcopydb/run/tables/80851245.done does not exist. But I see there is a file:
    /tmp/pgcopydb/run/80851245

I tried excluding the table associated and then the error came in another table.

Any suggestion about what is the problem?

**Comment by dimitri** [comment]
```
INFO Running pgcopydb version 0.10
```

The current version of pgcopydb is version 0.16. See https://github.com/dimitri/pgcopydb/releases. Only the current release is supported. Please see about how to install the current version of pgcopydb in the docs at https://pgcopydb.readthedocs.io/en/latest/install.html and try again.
